package.json
renderer/views/app.js
renderer/views/header.js
renderer/views/player.js
renderer/views/torrent-list.js

As of this PR (substack/hyperx#22) to `hyperx`, html attributes are automatically converted to properties for the few cases where they’re different: `class`, `for`, and `http-equiv`.
So, let's change `<div className="">` to `<div class="">`.
Also, I changed all the fancy `<div.my-class>` to `<div class="my-class">` so it's just normal html which is easier to understand, I think. It's less succinct, but it's also clearer and matches the rest of the other attributes that will be in the tag.

Use class instead of className; use standard html

---

renderer/index.js
renderer/views/player.js

function references in hyperx need to look like:
```
onloadedmetadata=${onLoadedMetadata}
```
and not:
```
onloadedmetadata="${onLoadedMetadata}"
```
also removed some unnecessary `torrent.ready` checks in the player.
> fixes #17

autoresize window on play

---

renderer/index.css
renderer/index.js
renderer/views/torrent-list.js

Now it's a little clearer which speed is upload and which is download, and you can also see total size and total downloaded in bytes so far.

improve torrent metadata display

---

package.json
renderer/index.js

From `main-loop`:
> main-loop is an optimization module for a virtual DOM system.
Normally you would re-create the virtual tree every time your state
changes. This is not optimum, with main-loop you will only update your
virtual tree at most once per request animation frame.
> main-loop basically gives you batching of your virtual DOM changes,
which means if you change your model multiple times it will be rendered
once asynchronously on the next request animation frame.

Batch virtual-dom changes (fix #27)

---

main/index.js
main/ipc.js
main/menu.js
main/shortcuts.js
package.json

Uses https://npmjs.com/package/electron-localshortcut to workaround a
bug in Electron (https://github.com/atom/electron/issues/1334).
We can remove `electron-localshortcut` once that bug is fixed.

Add alternate fullscreen shortcut ⌘+Shift+F (fix #26)

---

main/ipc.js
renderer/index.js
renderer/views/app.js

This change does the following:
- Prevent the window from resizing when in fullscreen because that just behaves weirdly.
- Show the header on Linux/Windows when fullscreened, but not in the
player. Users might fullscreen the app when they’re not playing a video.
- Always show the header on OS X (even when fullscreened) since that’s
how the user will exit the video. We can work on adding auto-hiding to
it later.

Fullscreen fixes

---

renderer/views/torrent-list.js

Tiny adjustment for progress bytes.
Ensures that at 0 or 100%, progress will not show duplicate values. So no `0 B / 0 B` or `129.4 MB / 129.4 MB`. Instead it looks like this:

improve progress percent & bytes display

---

renderer/index.css
renderer/index.js
renderer/views/app.js
renderer/views/header.js

This makes the header disappear right away when the mouse leaves the window, instead of waiting for the inactive mouse timeout.
This way the header matches what the controls do.

header disappear when mouse not over

---

package.json
renderer/index.js
renderer/state.js

Using `application-config` for now. So far working great. Storing magnet URIs of torrents in config instead of `.torrent` file paths since those are often deleted.
Played around with some different ways to capture and save torrent info until I realized I could just save info from `state.client.map` with the props I wanted on every client `torrent` event. That way no deduping is necessary. The WebTorrent client always tells the truth.
> resolves #24

add persistent app config

---

renderer/index.js
renderer/state.js

* Clean up `index.js`
* Separate `state.saved.torrents` from the list of currently active torrents (`state.client.torrents`)
This prepares us to support torrents which are not currently downloading -- such as the default videos that will show when Webtorrent.app is first installed. Such torrents are in `state.saved.torrents` but not in the active torrents list.
* Make the Blender Foundation videos show up by default
* Add a small Download button next to the big Play button
This starts / pauses the torrent download. While downloading the Play button will pulsate to show activity. Once the torrent is fully downloaded it will be solid green, to show that we're done and are now seeding. The button will act as a toggle--if you turn it off, it turns grey to indicate that the torrent is not …

Save and load torrents, document index.js

---

package.json
renderer/index.js

`updateThrottled` uses `setTimeout`/`clearTimeout` to ensure `update` is called at most once a second, but then we call `updateThrottle` exactly once a second anyway!
that's equivalent to calling `update` once a second directly

Remove updateThrottled

---

renderer/index.css

Addresses #42.
Playing around with linear gradients from http://uigradients.com. This one looks pretty good to me so far:
Could use improvement but it's better than all black :)

better default torrent bg

---

package.json
renderer/index.js

This PR does a few things:
- loads state before initializing app
- wraps IPC setup in a function called by `init()` to avoid a race condition where `update()` gets called too soon
- moves resuming of saved torrents into a function
- removes an unnecessary `console.log`
Loading state first allows setting defaults and preferences first (setup for #53).
Side thought:
Wondering if it might be faster to load app with less going on upfront (just header and empty list initialized) then send saved state over IPC from the main process. Startup is pretty slow for me at this stage and I feel like there's not enough going on in the UI to warrant that.

load state first

---

main/ipc.js
main/windows.js
renderer/index.js

See my comment here for background: https://github.com/feross/webtorrent-app/issues/3#issuecomment-193559568
- Show window without 50ms timeout (faster startup)
- Hide top menu bar unless Alt key is pressed (Windows, Linux)
- Leave fullscreen when player closes
- Don't resize window if maximized (when player is opened)

Fix Windows UX issues

---

renderer/views/torrent-list.js

Closes #50
Is this too clever?

prettier bytes: drop fractional number if integer side is more than one digit

---

main/ipc.js
main/menu.js
main/windows.js
renderer/index.css
renderer/index.js
renderer/state.js

- Fix fullscreen behavior on Windows
- The win.isFullScreen() function takes a second to return the correct value after going into fullscreen, so we should just pass the state manually into onToggleFullScreen().
- Update player window title correctly (to match torrent name) on OSs that use that native OS chrome (Windows, Linux). Before it only worked on OS X.
- This also moves all the state “diffing” for purposes of updating the app’s window via Electron APIs into one function `updateElectron()`. `state.prev` is used to store the previous values for diffing purposes.
- This is necessary because there's no `virtual-dom` for the Electron app state like dock progress, window title, etc. We don't want to just keep re-calling these OS system calls every time `update()` is called since that's a …

UI polish (Windows fullscreen, Linux/Windows player window title)

---

main/windows.js
renderer/index.css
renderer/index.js
renderer/views/torrent-list.js

* Download button is a lot easier to read: white down arrow when off, animated and pulsating green down arrow when downloading, solid green up arrow when seeding
* Play button shows a spinner if you click play before a torrent is ready, then an exclamation point if the torrent still isn't ready after 10 seconds
* Drop target shows up always, not just when the torrent list is empty. Lights up when you drag something
* Fixed alignment, the Xs to delete torrents are now aligned with the + to add a new torrent

Torrent list styling

---

package.json
renderer/views/torrent-list.js

This switches to use a just-published package `prettier-bytes` which does the same thing.
https://github.com/flet/prettier-bytes
It also cuts the decimals to a single digit per @rom1504's comment in #50
I'll also add @feross @rom1504 and @yoshuawuyts as collaborators/npm publishers in case folks want to tweak it more.

switch to prettier-bytes

---

renderer/index.js

Fix for small oversight in @dcposch’s recent changes. Broken when
adding the distinction between active and inactive torrents.
Please code review, @dcposch

Fix seeding functionality

---

renderer/views/player.js

Sets the video's state to paused when the `onended` event fires.

Fix looping video

---

renderer/index.css
renderer/index.js
renderer/state.js
renderer/views/app.js
renderer/views/header.js

Native windows get lighter when they’re backgrounded so they stand out
less (at least on OS X). Let’s do this too.
Even the Spotify app, which has dozens of developers gets this wrong.
We’re so awesome :)
Also:
- Renamed a bunch of state variables (next time will make separate
commit, sry)
- All window-related variables (e.g. isFullScreen, isFocused, etc.)
live in `state.window` now
- Remove negative class name, use CSS :not() instead

Lighter window background; small state changes

---

renderer/index.css

This is still the native scroll bar, not some JavaScript-custom-scroll monstrosity. It's just styled to match the app better.
Before: 
After:

Add custom styles to scroll bar

---

main/ipc.js
main/shortcuts.js
renderer/index.js

The ‘clipboard’ module works in the renderer without using the ’remote’
package. So we can eliminate one IPC call this way :)

Move paste to renderer

---

main/windows.js
renderer/index.js
renderer/views/player.js

`sendSync` is throwing an error currently as it does not exist.
This PR adds logic to signal the video to stop playing and only hide after we're sure the video is paused. 
Feedback appreciated!

ensure video is paused before hiding window

---

README.md

I definitely don't want to build for all three platforms every time I'm testing :)

add platform-specific package instructions

---

main/ipc.js
renderer/index.js
renderer/views/player.js

Using `video.onplay`, `video.onpause`, `dispatch`, `ipc` messages, and `electron.powerSaveBlocker`. I tested for unexpected errors getting thrown but haven't sat around waiting for the display to go to sleep yet. My belief is that it will Just Work™.
> fix #106

Block "Power Saver" mode while video is playing

---

bin/package.js
renderer/views/torrent-list.js

* Work around a Chrome bug by avoiding Windows-specific backslash paths
* Change the name of the program from "Streaming torrent client" to "WebTorrent"

Fix Windows packaging

---

README.md
bin/package.js
main/index.js
renderer/index.js

- OS X: Dock icon accepts drops of all file types -- seeds non-torrent files (fix #156)
- OS X: Register app as "Owner" of .torrent files (gives app priority for opening .torrent files)
- OS X: Add copyright statement to About window

Dock icon should accept all file types

---

index.js
main/index.js
main/ipc.js
main/menu.js
main/shortcuts.js
main/windows.js
renderer/index.js

Fixes #154
Also, use `console.time()` to time app startup.

Fix Exception when dropping .torrent file onto Dock icon when app is closed

---

config.js
main/index.js
main/ipc.js
main/register-protocol-handler.js
package.json
renderer/index.js

This is for #77.
This uses [`winreg`](https://www.npmjs.com/package/winreg) to modify the registry. I've used this package before for `webtorrent-cli`, to locate the path to launch VLC. `winreg` is great because it just calls out to the `REG` command line program with `child_process`, so it's pure JavaScript. No native deps. We want to avoid native deps in this app. So far we have none -- let's keep it that way.
Also:
If app is running in “production” (i.e. it has been packaged), then it will be invoked with one less argument.
WebTorrent.exe arguments
vs.
electron.exe /path/to/app arguments
We need to detect this to correctly handle `process.argv` command line arguments.

Windows: register protocol handler for magnet links

---

renderer/index.css
renderer/views/app.js

- fixed hide on hover (`state.video.location` should be `state.playing.location`)
- showing scrubber without needing to hover on playback bar
- added 5px of margin right to full screen button to even things out a bit
Now hover looks like this (same):
Without hover (playback time is now visible):
After 2 seconds (controls hide after delay again as they should):

fix hide on hover, always show playback position

---

bin/package.js

The old bundle ID ended in .app, which OS X will interpret as an
executable app. This meant that our preferences folder was treated like
an app, lol.

OS X: pick a better bundle ID

---

main/index.js
main/windows.js

Requires a workaround for this Electron issue:
https://github.com/atom/electron/issues/4338

Show, unminimize, and focus window after opening magnet link (fix #210)

---

renderer/state.js

This keeps them working if a user opens the app from DMG, then installs it to a different path and opens it again

Use relative paths for default torrents

---

main/ipc.js
main/menu.js
main/shortcuts.js
renderer/index.js

`globalShortcut` will register the shortcut at the OS level, even when
the app is not focused.
Using `localShortcut` would work, but let's put it in the top menu
instead, where all the other shortcuts are.

Keyboard shortcuts: volume shortcuts should be local

---

bin/cmd.js
bin/package.js
package.json

cmd.js is mostly taken from node_modules/electron-prebuilt/cli.js (what the node_modules/.bin/electron symlink points to)
I'm not 100% sure what it will do to the package.js though. It might be needed to add some exclude for electron-prebuilt in there.

add binary, fix #247

---

renderer/index.css

Before, if you scrolled so that the bottom placeholder wasn't visible, there was no indication that the app is still a drag target.

UX polish: highlight drag-drop even when placeholder isn't visible

---

main/handlers.js
main/index.js
main/squirrel-win32.js

- OS X: Register as default handler for "magnet" on startup
Also:
- Log errors in the renderer process, like the rest of errors in the
main process
- Windows: Less chance of registry write race condition
- Windows: register protocol handlers on startup

	OS X: Use app.setAsDefaultProtocolClient

---

main/index.js
main/squirrel-win32.js
main/tray.js

Fixes #288
This also cleans up the code by handling quit in the same way for all
platforms, removing the special case in tray.js for darwin.
We already have a 'before-quit' handler in main/index.js, so this is
now handled there :)

Windows/Linux: Fix broken Quit option in Tray icon

---

bin/package.js
package.json

Instead of "webtorrent-desktop_0.2.0-1_amd64.deb", name it "WebTorrent-v0.2.0.deb" like the rest of the built files.

Name the .deb file consistently

---

bin/package.js
package.json

package naming is handled by packager to follow debian convention
updated `nobin-debian-installer` to latest version (with your PRs) to handle change of name if needed

Follow debian package name convention

---

bin/package.js
config.js
main/handlers.js
main/menu.js
package.json

- Name Setup.exe with WebTorrent Desktop version number
- Don't generate .msi file (it's not a real .msi, only meant for Enterprise group policy)
- Hardcode remote releases URL to ensure that delta packages get built correctly even if the previous built files don't exist on the build machine
- New update URL: /desktop/update
- Windows: Add valid iconUrl – for building on non-Windows platforms

Windows Installer improvements

---

bin/clean.js
main/handlers.js
main/index.js
main/squirrel-win32.js
package.json

Now we can call `handlers.uninstall()` to remove the .torrent file and magnet link associations. This gets called in the Windows uninstaller.
On Windows, the registry entries are removed ONLY if they still refer to WebTorrent Desktop.
On Linux, the .desktop and icon files are removed.
On OS X, there is no way to remove the association explicitly. Removing the program is sufficient.

Uninstall handlers on Windows uninstall/npm run clean

---

config.js
main/handlers.js
main/index.js
main/squirrel-win32.js
package.json
renderer/index.js

This helped me to debug why Electron 0.37.4 was crashing. Turns out that 0.37.4 has a broken Buffer implementation and it seem is (accidentally) using a pre-release version of Node 6. Whoops!
In any case, crash reporting is useful. Going to leave this in.
Server-side components to the reporting are in this PR: https://github.com/feross/webtorrent-www/pull/52

Add crash reporting

---

renderer/index.css

They make the app feel too much like a webpage. I don't like the UI
jumping around as I resize the window.

Remove media queries

---

renderer/index.js
renderer/lib/cast.js

Fixes #208 
@feross LMK if you think there's a cleaner way to do this
Also avoids loading all of the cast modules (chromecast/airplay/dnla) the first time you play/pause/seek a video when you're not casting.

Show video controls immediately on mouse move

---

renderer/webtorrent.js

Add `client` (the WebTorrent client) and `server` (the WebTorrent-to-HTTP streaming server) to the window, so it's available in Dev Tools.

Make WebTorrent process easier to debug

---

renderer/lib/torrent-poster.js

Fixes #341 (Thanks @gdelavald!)
When a 0-byte image is retrieved from a video file to be used as a buffer, the function now creates an error. This prevents the application from producing the unexpected behavior of displaying a *black* background, as opposed to the desired blue gradient.
This happens when the video file used is composed of just audio. When the audio waveform poster generation for sound files is implemented, we may want to trigger that instead, but for now this works fine.

Create error on zero-byte poster

---

CHANGELOG.md
config.js
main/windows.js
renderer/index.js

For audio-only .mov files, which are 0x0.
Closes #340

Enforce minimimum window size when resizing player

---

main/windows.js
renderer/index.js
renderer/lib/location-history.js

Before, if you were in the middle of playing a video and closed the window, the app would actually just pause the video and minimize to tray ---- so if you reopen the window a day later, the video is still there!
This fixes that.

Exit media when user closes window

---

main/ipc.js
main/windows.js

This was a rare race condition during app shutdown where a 'wt-'
message would be sent from the hidden webtorrent window to the main
window after the main window was already closed.
Fixes #373

Fix JS error on app quit

---

renderer/index.js
renderer/lib/dispatcher.js
renderer/lib/location-history.js
renderer/lib/sound.js
renderer/views/player.js

Before this change, the player would just get stuck on the loading
screen forever without notifying the user.

Show error when media format is unsupported

---

renderer/index.js
renderer/lib/cast.js
renderer/views/player.js

I found it awkward to listen to the video tags 'playing' and 'paused'
events, when we're controlling the state that defines what state it's
in in the first place.
This commit removes those listeners, in favor of just setting things to
the right state immediately when play(), pause(), or playPause() is
called.
Added play(), pause() methods for clarity.

Simplify play/pause handling

---

README.md
bin/package.js
bin/release-_pre.sh
config.js
main/index.js
package.json
renderer/index.js
renderer/state.js

Fixes https://github.com/feross/webtorrent-desktop/issues/358
- [What is a portable app?](http://portableapps.com/about/what_is_a_portable_app)
- [Portable Audacity](http://wiki.audacityteam.org/wiki/Portable_Audacity)
- A new `*-win.zip` output file is now produced, which just contains the electron-packaged windows app, with an added empty "Portable Settings" folder.
- At startup, when a "Portable Settings" folder is found next to the WebTorrent.exe file, then the app is in "Portable Mode" which entails:
- Electron "userData" folder is set to the "Portable Settings" folder
- The `config.json` file is saved in the "Portable Settings" folder
- Torrent posters and torrent files are saved in the "Portable Settings" folder
- The default download folder is set to the "Portable Settings" folder …

Windows Portable App

---

package.json

I was working with srt-to-vtt and to-utf-8 projects to implement proper non-UTF-8 support for srt files.
This handles another item in #281

Multiple srt charset encoding support

---

renderer/webtorrent.js

Fixes #386
**When pasting an invalid magnet link**
Before: nothing happens, no indication about what went wrong
After:

Show an error when adding an invalid magnet link

---

renderer/index.js
renderer/webtorrent.js

This works around a WebTorrent bug where calling client.add(torrentFilePath) to add a duplicate torrent -- in other words, one whose infoHash we're already torrenting -- creates a new torrent object and later throws an error. Inconsistently, calling client.add(magnetURI) or client.add(infoHash) to add a duplicate torrent returns the existing torrent object that we're already torrenting and doesn't throw an error.
This also fixes a prety nasty bug where pasting a dupe magnet link changed the torrentKey of an existing torrent, breaking the communication between the main and WebTorrent windows
Fixes #364

Show an error when adding a dupe torrent

---

main/ipc.js
renderer/index.js
renderer/views/torrent-list.js

Based on @watson's PR #463.
Differences:
- Remove the "Open Folder" link from expanded torrent view.
- Use showItemInFolder instead of openItem electron API
- Add a separator
- Use IPC to invoke electron.shell.showItemInFolder from main process

Add "Show in Folder" to context menu

---

main/windows.js
package.json

When selecting "Open Torrent File..."
Before:
After:

Set sheet offset

---

bin/open-config.js
package.json
renderer/index.js

Running `npm run open-config` will open the `~/Library/Application Support/WebTorrent/config.json` file on OS X, etc. etc. on other OSes.

add `npm run open-config` to open config file quickly

---

main/windows.js

win.setSheetOffset at main/window.js is undefined on non OS X environments. 
Just guarding against TypeError

Avoid TypeError out of OS X

---

crash-reporter.js
index.js
main/index.js
main/ipc.js
renderer/index.js
renderer/webtorrent.js

WebTorrent 0.91 changed how duplicate torrents are handled, which broke
handling in WebTorrent Desktop.
After this PR:
- No more try-catch on client.add -- this method has never thrown errors.
- No check for duplicate torrent.key value since client.add no longer
returns the same torrent object when adding a duplicate torrent. It
emits 'error' instead, and that case is already handled :)

Fix duplicate torrent handling

---

main/windows.js
renderer/index.css
renderer/views/torrent-list.js

The goal of this PR is to make the UI more compact. WebTorrent Desktop's UI is currently a lot larger than a lot of the other apps I use on a daily basis. This makes it harder to manage even a moderate number of torrents.
- Reduce torrent list item from 120px to 100px height
- Reduce font sizes (torrent list, modal labels)
- Make default window height big enough to show all torrents
Other UI improvements:
- Vertically center torrent list buttons
- Merge the two torrent status lines onto a single, concise line
- Hide download speed, upload speed, and number of peers when 0, because that's just noise.
- Remove number of files, because that information can be found by expanding the torrent.
Before | After
----------|-------
Detailed view:

UI tweaks: Reduce font size, list item height, single torrent status line

---

main/ipc.js

This is deprecated usage and was just removed in Electron v1.

Remove require('screen')

---

config.js
main/ipc.js
main/menu.js
main/shortcuts.js
renderer/index.js

The goal here is to remove shortcut handling from the renderer and
unify it all in menu.js and shortcuts.js (for alternate shortcuts).
- Added Playback menu with:
- Play/Pause
- Increase Volume (moved from View menu)
- Decrease Volume (moved from View menu)
Also:
- Code cleanup to make menu.js more internally consistent.
- Name the electron.dialog returned value `selectedPaths` which is more accurate.
- Move the file menu into the `template` object, like the rest of the menus. Then reach in afterwards for OS-specific tweaks.
- Fix bug: Space key triggers power save block from torrent list

Shortcuts improvements

---

main/ipc.js
main/menu.js
renderer/index.js
renderer/state.js

This bug was subtle. Basically, on OS X only, we use
window.setAspectRatio() to make the player window match the video size.
But this is maintained even in fullscreen mode, which makes the window
actually not use up the fullscreen, and there are black bars above and
below the video player controls, which looks really weird.
Unset the aspect ratio in fullscreen mode, then set it again upon
leaving fullscreen mode.

OS X: Make controls use full window in fullscreen

---

renderer/index.css

Before this PR, grabbing the volume slider nub would move the window.

OS X: Volume slider nub should not move window

---

config.js

In the renderer process on OS X, config.IS_PRODUCTION was always true
because process.execPath is to "Electron Helper", so the detection
regex was being overly specific.

Fix isProduction() detection

---

renderer/index.js

Fixes #448 
**We should test this on Windows before merging.**
**Test plan:**
1. Delete config.json
2. Install the current released version
4. Run, add a torrent, then quit
5. Run from this branch. Both default torrents and the new one you added should still work
6. Repeat 1-5 on Windows and on posix (Mac or Linux)

Fix torrentPath migration

---

bin/package.js

Background on this change: https://github.com/feross/webtorrent-desktop/issues/437#issuecomment-219172469
It appears that the Atom team just ships a 32-bit binary to all Windows users.
https://github.com/atom/atom/issues/4881
Let's do the same, for now. This single 32-bit binary will work just fine on 32-bit and 64-bit Windows.

Only build 32-bit binaries for Windows

---

renderer/index.js

Fixes a bug in our drag-drop handling: before, it was impossible to create a torrent containing .torrent, .srt, or .vtt files

Allow seeding torrents that contain subtitles

---

renderer/webtorrent.js

HACK: OS X: Disable WebRTC peers to fix 100% CPU issue caused by Chrome
bug.
Fixed in Chrome 51, so we can remove this hack once Electron updates
Chrome.
For #353.

HACK: OS X: Disable WebRTC peers to fix 100% CPU issue

---

renderer/index.js

We need to check if the label ends with the string representation of a number
If you use Number.isNaN this happens
because Number.isNaN checks if the parameter is a numeric type

check if the subtitle label ends with a number

---

renderer/index.js

Push page into location right away

OS X: Fix magnet links throwing exception on launch

---

renderer/views/create-torrent-page.js

Single-file torrents seeded in place correctly, multi file torrents did not.

Fix a bad bug when creating multifile torrents

---

package.json
renderer/index.js
renderer/state.js
renderer/views/create-torrent-page.js
renderer/views/player.js
renderer/webtorrent.js

Better subtitles support

---

renderer/index.css
renderer/index.js
renderer/views/torrent-list.js
renderer/webtorrent.js

Saves bandwidth and disk space when a torrent contains extra files you don't need
Fixes #360

Allow selecting individual files to torrent

---

renderer/index.css
renderer/views/torrent-list.js

Apparently that's only for websites & we want to feel native

Remove `cursor:pointer`

---

renderer/index.js
renderer/views/app.js

Later, in a separate PR, we'll make it so that Webtorrent Desktop remembers your position in the videos you've watched. That way, it won't be as bad to automatically exit ppl out of their video.

Always handle when the user clicks a magnet link or torrent file, or uses File > Open Torrent

---

renderer/index.js
renderer/lib/location-history.js
renderer/views/app.js
renderer/views/create-torrent-page.js
renderer/views/header.js

Lots of intertwined changes here, might be easier to review commit-by-commit.
---
I don't think it matters whether the open comes from onOpen (opening
magnet, .torrent file, dragging file to dock, menu item) or from
dragging to the window.
These should use the same code path. The only relevant information is
the page of the app that we're on.
This change unifies the two methods, and supports dragging .torrent
files or creating a torrent when the player is active, if the dragged
files are not .srt or .vtt. We go back to the list, or to the create
torrent page in these situations, so it's not confusing for the user.
Always close open modals when handling an open.

Improve open behavior; Fix bugs in LocationHistory

---

main/ipc.js

- Start video on top, so it's not obscured by other windows.
- Don't show "video title" which is just "http://localhost:xxxx"
- return after error

VLC tweaks

---

config.js
main/announcement.js
main/index.js
main/updater.js

If there's a message returned by the given remote URL, then it will
show up for the user.
Useful in situations where the auto-updater is not working, or if
there's a security issue.

Add announcement feature 

---

bin/package.js

Before this change, .torrent files would only be associated to
WebTorrent Desktop if another torrent client (like Transmission) was
installed on the system.
That's because one of the user's apps needs to define
"UTExportedTypeDeclarations".
On a fresh machine, without Transmission, WebTorrent Desktop now
associates .torrent files correctly.
So it will appear in the "Open With..." menu and the webtorrent
.torrent icon will be used for .torrent files.
Closes #542

Associate .torrent files to WebTorrent Desktop (OS X)

---

renderer/index.css
renderer/index.js

Before this commit, we tweaked the subtitle position by modifying the
VTT file, line by line with a regex because I did not know it was
possible to use CSS for it.
But apparently there are Shadow DOM elements that we can use instead.
This new approach improves:
- Wrapping long lines. Before, the text would go off the edge of the
screen. Now it wraps intelligently.
- The subtitles move up to get out of the way of the controls when
those are visible.

Improve subtitle positioning

---

renderer/views/torrent-list.js

One more bit of cleanup for PR #529.
We can register `handleClick` once on the `<tr>` tag and just have the
onclick handler on `col-select` too. Because dispatcher calls
`event.stopPropagation()` we don't need to worry about event bubbling
up to the `<tr>`.

Fewer click handlers

---

package.json

No new features that affect us.
This release includes Chrome 50, which should improve the webrtc CPU usage situation on Linux. For the OS X improvement, we're still waiting for Chrome 51.

electron-prebuilt@1.1.1

---

renderer/lib/torrent-poster.js

Use `poster.jpg` file as the poster image if available.

---

renderer/views/player.js

Notifies when a video codec is not supported (such as H.265 in #561), and allows it to be played in vlc similar to how unsupported audio in videos are already handled.

Handle unsupported video codec (e.g. H.265)

---

renderer/index.js

Right now, clicking Play on one of the default torrents doesn't work, because they don't have `defaultFileToPlay`
Torrents can exist in one of a few states. Maybe we should make this more explicit in a future PR to help prevent future bugs. Possible states:
1. New default torrent. These have a list of files and infohash, but no `path`, no full torrent metadata, no `progress`, and no `defaultFileToPlay`
2. Newly added magnet link. These have an infohash and basically nothing else. They show up as "Loading torrent..."
3. Newly added files to seed. These have a list of files and basically nothing else, not even an infohash.
4. Normal torrent. These have everything as well as a `progress` object to track downloading / seeding.
5. Stopped torrent. These have everything except a `progress` …

Bugfix: pick default file to play on default torrents

---

main/menu.js
package.json
renderer/index.css
renderer/views/app.js
renderer/views/header.js
renderer/views/player.js

Tried to match the YouTube player UI more closely. There's still work to do, but this is a huge improvement for consistency:
Compare to:
- Increased size of all controls
- All buttons consistently get lighter on hover, without redundant css
- Play button moves to left, just like YouTube
- Time tweaks: thinner font, less verbose (0:xx instead of 00:xx, and omit hours when they're 0)
- Bigger volume slider nub
- Show back/forward buttons in top left on Windows/Linux, when in player
- So it's consistent with OS X version, and the back button doesn't move around
- Also, there are technically situations in which the forward button is needed from the player
- Like if you start creating a torrent from the player, then go back, then want to go forward again
- Make the background of the header bar …

More consistent controls

---

main/menu.js
renderer/index.css
renderer/index.js
renderer/state.js
renderer/views/app.js
renderer/views/header.js
renderer/views/preferences.js
renderer/views/torrent-list.js

I took what @ChrisMorrisOrg started, get some feedback from #62 and this is what you get.
Its not as clean as i want, but is what i get.
Feel free to comment.
The whole idea is to implement a preference section with reusable components (file selector, text, checkbox) and pass parameters to them.
The only active right now is Download Path (help text needs rewording)
Also, commented is a checkbox preference (Tray disable) which is not working, but you can comment out and see how the pref is saved.
You can also see how a section will be displayed
@dcposch @feross feel free to use the branch to make the change you want.

Add Preferences Support

---

renderer/webtorrent.js

Tested on OS X, Windows. No immediate crash.
Let's merge to master so we can test all day today to see if the 100% CPU issue is gone from OS X for good. Closes #353.

Re-enable WebRTC (OS X, Windows)

---

package.json
renderer/lib/cast.js

This PR is currently WIP and meant as a way of tracking the progress of improving the AirPlay support.
This PR uses the [airplayer](https://github.com/watson/airplayer) module instead of [airplay-js](https://github.com/guerrerocarlos/node-airplay-js).
As far as I can see, the main feature differences between the two modules currently are:
- airplay-js serves the video using HLS, airplayer just streams the video using HTTPS range requests
- airplay-js supports using ffmpeg (if present on the OS) to transpile and cut up the video into smaller pieces to be served as an HLS playlist. Airplayer does not use ffmpeg, so does not support transpiring, but will therefore use significant less CPU for videos that does not need to be transpiled
- airplay-js supports subtitles if ffmpeg is used
- …

Use airplayer

---

main/tray.js

Note: There is still an issue with the tray, when the WebTorrent app is hidden, the tray item "Hide to tray" does not change to "Show WebTorrent", but I can't seem to figure out how to fix it.

Fix issue with tray on Windows.

---

main/menu.js
main/windows/main.js

Fixes #608.
Should the menu item `Float on Top` be renamed to `Always on Top` as the function?

Fix 'fullscreen' and 'always on top' menu items

---

main/dialog.js
main/ipc.js
renderer/main.js
renderer/views/header.js

Making the add button consistent with drag and drop as described in #246, is this correct?
Note that the `openTorrentFile` dispatch is no longer used, should it be removed?

Make add button accept non .torrent files (seeding)

---

package.json
renderer/lib/migrations.js
renderer/lib/state.js
renderer/main.js

- Put migrations into a separate file: migrations.js
- Add semver, for more specific version-based migrations.
- Change `state.saved.version` to semver app version.
Also:
- Fix exception caused by incorrect file ordering  https://github.com/feross/webtorrent-desktop/pull/604#issuecomment-222805214

Semver-based migrations

---

renderer/main.js

I took a look at the issue #581 i created about adding a stopped torrent that is already in the list.
I was able to fix the issue by replacing the torrentKey of the first torrent with the key of the duplicate, and mimic a toggleTorrent.
This is not an elegant solution, but maybe it could do for now?
Also, I was wondering why a torrent have a torrentKey instead of being identified by the infoHash?

Adding duplicate torrent when stopped

---

renderer/main.css
renderer/views/player.js

https://github.com/feross/webtorrent-desktop/issues/467
The icon name is "closed_caption", not "closed_captions"
http://jsbin.com/fenejob/1/edit?html,output
The extra space we're seeing is the icon font rendering the 's', which
renders as nothing.

Use correct icon name

---

bin/package.js
main/index.js
main/ipc.js
main/log.js
main/windows/about.js
main/windows/main.js
renderer/main.css
renderer/main.js
renderer/webtorrent.js

This should eliminate startup bugs caused by `ipcReady` being sent too eagerly from the renderer. I originally moved `ipcReady` to as early as possible in order to make the app launch faster.
But if we make the window show by default, instead of being hidden and waiting for `ipcReady`, then startup doesn't actually feel any slower.

Fix IPC race condition in startup 

---

package.json

Full changelog here: https://github.com/electron/electron/releases/tag/v1.2.1
The main benefits to us is "Fix crash caused by calling `BrowserWindow.setAspectRatio(0)`"

electron-prebuilt@1.2.1

---

main/menu.js

We got this feature idea from VLC, so let's align with the keyboard
shortcuts that they use :)
Closes #618.

Change step Forward/Backward shortcuts to match VLC's

---

main/windows/about.js

Shows up as 'Electron' on Windows

Fix title in About Window

---

renderer/main.js

Fixes #598.
This could also be done using the already implemented `state.window.isFocused`, however I added a `webkitvisibilitychange` event listener, since we only need to force the render when the window is completely hidden and not just out of focus. The event does not fire often so I think this is reasonable.

handle play/pause when window is hidden

---

renderer/main.js

Fixes a bug where you could create duplicate torrents by adding the same folder multiple times, because the file order & therefore the infohash was nondeterministic

Seeding: sort files by path

---

bin/package.js
main/handlers.js
renderer/main.js
static/linux/webtorrent-desktop.desktop

Related to  #83 
Only tested on Windows.

new protocol handler: stream-magnet

---

renderer/views/player.js

Previously, the following error was thrown on player open:
```
rendering error: Cannot read property 'false' of undefined
TypeError: Cannot read property 'false' of undefined
at D:\Workspace\webtorrent-desktop\renderer\views\player.js:439:43
at Array.forEach (native)
at renderPlayerControls (D:\Workspace\webtorrent-desktop\renderer\views\player.js:418:13)
at Object.Player (D:\Workspace\webtorrent-desktop\renderer\views\player.js:22:9)
at getView (D:\Workspace\webtorrent-desktop\renderer\views\app.js:81:20)
at App (D:\Workspace\webtorrent-desktop\renderer\views\app.js:44:30)
at render (file:///D:/Workspace/webtorrent-desktop/renderer/main.js:126:12)
at redraw (D:\Workspace\webtorrent-desktop\node_modules\main-loop\index.js:65:23)
at …
```

[Urgent] Fix error in renderer/views/player.js

---

renderer/views/player.js

Previously, `state.playing.jumpToTime = 0` didn't do anything. This commit fixes that.

Fix state.playing.jumpToTime behavior

---

renderer/lib/telemetry.js

Also fix a bug where Remove Data File doesn't work when the first file in the torrent is in a subfolder.

Only send telemetry from production

---

renderer/controllers/playback-controller.js
renderer/controllers/subtitles-controller.js
renderer/main.js
renderer/views/player.js

Fixes #701.
The selected subtitle index is stored in the same way as the current time of the playing file. It might be overkill to do this on every render, but I could not see other obvious places to put it, since subtitles can be added/selected in multiple ways.

Save selected subtitle

---

renderer/lib/telemetry.js
renderer/main.js

When I tried to play an unsupported video the uncaught error was `undefined` for some reason.

Improve error logging

---

renderer/controllers/torrent-list-controller.js
renderer/main.js

Fix unhandled 'error' dispatch used by the `subtitles-controller` and `playback-controller`, and be consistent in the `torrent-list-controller`.

Fix unhandled 'error' dispatch

---

renderer/controllers/torrent-list-controller.js

Fix strange error where clicking 'Show In Finder' would also show the 'confirm delete torrent' modal. Also make it show the torrent content and not the cached torrent file.

fix showItemInFolder

---

package.json

This protects against corrupting the configuration file if the
application crashes before the stream finishes writing to the file
Especially important for large configuration files
See https://github.com/LinusU/node-application-config/pull/3

application-config@1

---

src/main/dock.js
src/main/menu.js
src/renderer/main.js

Followup PR to #738.
- Electron: Use default labels and accelerators
- macOS: add missing Edit menu roles
- Use 'quit' role
- Linux: Support showing badge count
Please review: @mathiasvr

Electron: Updates for Electron 1.2.8

---

package.json

Another Electron was just released. Let's bump from 1.2.8 to 1.3.0.
Changelog:
- Upgrade to Chrome 52
- Update to Node.js 6.3.0

electron-prebuilt@1.3.0

---

package.json
src/renderer/webtorrent.js

To distinguish WebTorrent Desktop (WD) from WebTorrent in the browser
(WW).
See the spec:
http://www.bittorrent.org/beps/bep_0020.html
https://wiki.theory.org/BitTorrentSpecification

Set peer ID to start with "-WD-"

---

.babelrc
bin/check-deps.js
bin/package.js
package.json
src/main/index.js

- Switch to babel, since react-tools has been deprecated since June 12, 2015. See https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html
- Move babel command to "npm run build"
- Move commands for package into "bin/package.js"

Replace deprecated `react-tools` with `babel`

---

package.json
src/main/windows/main.js

Fixes: https://github.com/feross/webtorrent-desktop/issues/565
This was trivial thanks to a new Electron API in 1.3.3, browserWindow.setContentBounds()

Update Electron to 1.3.3

---

src/main/ipc.js
src/main/menu.js
src/main/tray.js
src/main/windows/main.js
src/renderer/controllers/prefs-controller.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/main.js
src/renderer/views/create-torrent-error-page.js
src/renderer/views/create-torrent.js
src/renderer/views/preferences.js
src/renderer/views/torrent-list.js
src/renderer/views/update-available-modal.js

You can no longer open a whole stack of Prefs windows, or Create Torrent windows
Simplifies and fixes behavior when dropping files onto the app or the dock icon. Before, you could use drag-drop to create stacks of Create Torrent windows. Now, you can only create torrents from the home screen.
Fixes #665

Fix screen stacking bug

---

src/renderer/controllers/playback-controller.js
src/renderer/controllers/prefs-controller.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/state.js
src/renderer/main.js
src/renderer/views/preferences.js
src/renderer/views/torrent-list.js
static/main.css

Also handle the case where the user cancels out of Save Torrent File As
Fixes #646.

Check for missing download path

---

src/main/index.js

Ignore '.' argument, which gets misinterpreted as a torrent id, when a development copy of WebTorrent is started while a production version is running.

Ignore '.' argument which is annoying in development

---

src/main/power-save-blocker.js

Before this change, when opening the player, both 'onPlayerOpen' and
'onPlayerPlay' would fire, which enabled, disabled, and re-enabled the
power save blocker in quick succession.
Instead, we just want to activate it once.

If a power saver block already exists, do nothing

---

src/renderer/lib/telemetry.js

This ensures that people who keep the app running in the background
for days at a time are still counted as active users.

Telemtry: post at least once a day

---

src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/migrations.js

There was a terrible bug introduced in https://github.com/feross/webtorrent-desktop/commit/0809e20a6e1de917a2f8315c2f1da3b9ef177a43 -- clicking play on any of the default torrents in a fresh install of the app would fail and result in a 'path missing' error.
This fixes the bug, and also adds a migration step to clean up resulting broken config files

Fix playback + download of default torrents

---

src/renderer/controllers/playback-controller.js
src/renderer/pages/TorrentListPage.js

Fixes #810 
It might be cleaner to handle this directly in the PlaybackController`openItem` method, or to create a noop dispatcher function?

Don't open partially downloaded files in external app

---

src/renderer/pages/TorrentListPage.js

If the torrent folder has been deleted we show a path missing error and do not render the play and download buttons, however the radial progress (`positionElem`) was still being displayed.
This PR fixes that, but the `renderTorrentButtons` function could still use some refactoring.

Don't render radial progress on path-missing error

---

src/renderer/lib/state.js
src/renderer/main.js

Fixes #774.
Would it be better to initialize `prev.progress` in the default state?

Decrease setProgress updates

---

src/renderer/webtorrent.js

Noticed the webtorrent renderer instance has a `console.time('init')` with a missing `console.timeEnd('init')` counterpart. Thought I'd add it in at the end of the `init()` function.

fix: add missing console.timeEnd

---

src/renderer/pages/App.js

A require() had the wrong case, which apparently works for `npm start` build but fails in the packaged app
@noamokman @mathiasvr

Fix npm run package

---

src/renderer/lib/telemetry.js

Follow-up on #836. Ensures that e/stack/message is not undefined.
Also fixes a bug present in  #845 where the stack was `undefined`.

Telemetry: handle undefined values

---

src/renderer/pages/CreateTorrentPage.js

Trivial bug. When there are too many files in the Create Torrent screen, we currently say "+ -80 more" instead of "+ 80 more"

Fix Create Torrent file list

---

src/renderer/pages/TorrentListPage.js
static/main.css

#796 
Added simple progress bar using the build in <progress> html tag.
I hope this (minor) addition is usefull.

Added progress bar to the metadata on the overview

---

src/renderer/controllers/torrent-list-controller.js

Fixes #854
When starting WebTorrent 'new' torrents usually don't have any `.files` yet, causing an error when calling fs.stat with a null parameter.

Ensure that torrent file metadata is present

---

src/renderer/lib/telemetry.js
src/renderer/main.js

To follow up on #854.
Telemetry was not initialized early enough to catch this error. I moved it from `delayedInit` and didn't experience a noticeable change in startup time.
Another problem was that the stack trace was `undefined` because `e` was used instead of `e.error`, so I swapped the if statements.
Also it might be a good idea to `console.log` the uncaught errors, instead of only logging them for telemetry?
@dcposch

Early telemetry

---

src/main/dock.js

On each startup with `npm start` on Windows, the following error appears in the terminal:
```
TypeError: app.setBadgeCount is not a function
at Object.setBadge (C:\Users\Goldob\Projekty\NodeJS\webtorrent-desktop\build\main\dock.js:37:7)
at EventEmitter.ipc.on (C:\Users\Goldob\Projekty\NodeJS\webtorrent-desktop\build\main\ipc.js:52:43)
at emitTwo (events.js:106:13)
at EventEmitter.emit (events.js:191:7)
at EventEmitter.ipc.emit (C:\Users\Goldob\Projekty\NodeJS\webtorrent-desktop\build\main\ipc.js:150:13)
at EventEmitter.<anonymous> (C:\Users\Goldob\Projekty\NodeJS\webtorrent-desktop\node_modules\electron-prebuilt\dist\resources\electron.asar\browser\api\web-contents.js:156:13)
at emitTwo (events.js:106:13)
at EventEmitter.emit (events.js:191:7)
```
This PR fixes that by ensuring that we …

Fix error on Windows caused by `setBadge`

---

src/renderer/lib/telemetry.js

The following stacktrace slipped past our redaction:
```
Processes: webtorrent, platforms: win32, versions: 0.13.1 
RangeError: Array buffer allocation failed
at Buffer.Uint8Array (native)
at FastBuffer (buffer.js:8:1)
at createUnsafeBuffer (buffer.js:33:12)
at allocate (buffer.js:176:12)
at Function.Buffer.allocUnsafe (buffer.js:136:10)
at Function.Buffer.concat (buffer.js:326:23)
at C:\Users\Matt\AppData\Local\WebTorrent\app-0.13.1\resources\app.asar\node_modules\fs-chunk-store\index.js:200:23
at end (...\node_modules\run-parallel\index.js:16:15)
at done (...\node_modules\run-parallel\index.js:20:10)
at each (...\node_modules\run-parallel\index.js:26:7)
```
...notice how all lines except that middle one are redacted with a (...).
So yeah, we have at least one user named Matt :)
This …

Telemetry: fix stacktrace redaction

---

src/renderer/components/modal-ok-cancel.js
src/renderer/components/open-torrent-address-modal.js
src/renderer/components/path-selector.js
src/renderer/components/remove-torrent-modal.js
src/renderer/components/unsupported-media-modal.js
src/renderer/components/update-available-modal.js
src/renderer/pages/App.js
src/renderer/pages/create-torrent-page.js
static/main.css

Upgraded the four modals:
* Open Torrent Address
* Remove Torrent
* Unsupported Media (play in VLC)
* Update Available (Linux only, where we don't have an auto updater)
Also cleaned up the Create Torrent page, deleted some redundant CSS, prevented click-and-drag inside a TextField from moving the whole window, and made all label and input fonts  a consistent 14px size.
@feross @mathiasvr @noamokman

Material UI: upgrade modals

---

package.json

Hi,
This technically fixes #861.
Originally written in #837, but separated to a different PR.
Thanks!
@dcposch @jurgentreep

make "npm run watch" work on windows

---

src/renderer/controllers/playback-controller.js

This is a follow up for PR #871.
The intended behavior was that when opening player, playing some files and then navigating backward/forward in the app, the playback state is restored. In one particular case, when we open a specific file instead of a torrent and then do the above, the playback starts again at the same file it started at instead.
This PR fixes that.

Restore playback state when reopening player

---

.gitignore

Fix `.gitgnore` false negative for `npm-debug.log` file. Consistent with [GitHub's repo](https://github.com/github/gitignore/blob/master/Node.gitignore#L4).

Make git ignore npm-debug.log

---

src/main/ipc.js
src/main/menu.js
src/renderer/controllers/playback-controller.js

Disable playback controls while in external player

---

package.json
src/renderer/controllers/playback-controller.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/capture-video-frame.js
src/renderer/lib/cast.js
src/renderer/lib/errors.js
src/renderer/lib/sound.js
src/renderer/pages/torrent-list-page.js
src/renderer/webtorrent.js

* Moved most of the error definitions to dedicated `errors.js` file, which was hanging unused until now
* Created separate classes for different types of errors to increase verbosity and get rid of vague errors
* Fixed a typo in error name inside `playback-controller.js` possibly resulting in a `TypeError`

Move error definitions to `errors.js`

---

src/renderer/components/open-torrent-address-modal.js

Fixes a bug introduced in 0.14.0: clicking OK works, but hitting Enter doesn't do anything.
Showed up as an uncaught error in telemetry:
```
Processes: window, platforms: linux win32, versions: 0.14.0
TypeError: this.handleOK is not a function
at OpenTorrentAddressModal.handleKeyDown (...\build\renderer\components\open-torrent-address-modal.js:51:28)
at TextField._this.handleInputKeyDown (...\node_modules\material-ui\TextField\TextField.js:205:46)
at Object.invokeGuardedCallback (...\node_modules\react\lib\ReactErrorUtils.js:26:12)
at executeDispatch (...\node_modules\react\lib\EventPluginUtils.js:89:21)
at Object.executeDispatchesInOrder (...\node_modules\react\lib\EventPluginUtils.js:112:5)
at executeDispatchesAndRelease (...\node_modules\react\lib\EventPluginHub.js:44:22)
at …
```

Fix Open Torrent Address modal

---

src/renderer/components/header.js

Previously, moving the mouse into the player window from the sides or
bottom would bring up the HUD, but moving the mouse in from the top
would not. With this commit, moving the mouse in from the top of the
window will also bring up the HUD.
Fixes feross/webtorrent-desktop#241

Update mouse moved time on header hover

---

src/main/external-player.js
src/renderer/components/unsupported-media-modal.js
src/renderer/controllers/subtitles-controller.js
src/renderer/lib/state.js
src/renderer/pages/player-page.js
src/renderer/pages/preferences-page.js

* moved mac .app path mangling away from preference page.
* made `getExternalPlayerName()` convenience function to simplify code.
* + cleaned up the `addSubtitles` function a little.

External player clean up

---

package.json
src/main/index.js
src/main/ipc.js
src/main/startup.js
src/main/windows/main.js
src/renderer/controllers/prefs-controller.js
src/renderer/lib/state.js
src/renderer/main.js
src/renderer/pages/preferences-page.js

Rebases #837 
Adds two Mac-specific fixes:
* Don't show a Terminal window. (Used a variant of the workaround here: https://github.com/Teamwork/node-auto-launch/issues/28#issuecomment-222194437 )
* Start with the main window hidden (minimized)
Also, there's a new version of `auto-launch`, 4.0.1, that apparently fixes start-minimized on Windows.
@noamokman @feross

Start automatically on login

---

package.json

The changes that are relevant to us are:
- Upgrade to Chrome 53.
- Upgrade to Node 6.5.0.
- Add support for titleBarStyle: 'hidden-inset' on OS X 10.9.
The last item should improve our UI on OS X 10.9 since we use 'hidden-inset'. I don't know what it looked like before.

Electron 1.4.0

---

src/config.js
src/main/updater.js
src/renderer/lib/telemetry.js

Detect the actual operating system CPU architecture. This is different
than `process.arch` which returns the architecture the binary was
compiled for.
This is just good info to have in the telemetry, but we're also sending
it in the update check so that eventually we can upgrade Windows 32-bit
apps to 64-bit, like Slack does.
Context: https://github.com/feross/webtorrent-desktop/issues/873#issuecomment-247722023

Detect system architecture; send in update/telemetry

---

CHANGELOG.md
bin/package.js
static/about.html

Right now all Windows users are running a 32-bit app, even if their OS
is 64-bit. This means that the app is limited to a 4GB address space,
which may be contributing to the "Array buffer allocation failed" errors
we are seeing in the wild (#873).
If users on Windows 64-bit (90%+ of users) could run a 64-bit app,
they're less likely to run into out-of-memory errors.
Here's the plan to improve things:
1. We release a 64-bit installer, in addition to the 32-bit installer.
2. We auto-detect in the browser when a visitor is on a 32-bit vs.
64-bit OS and try to offer them the right installer. When in doubt, we
give them the 32-bit installer since that's safest.
3. The auto-updater will return the right binaries for the architecture
the user is on. This means that all our existing users who …

Add 64-bit Windows build

---

src/config.js
src/main/index.js
src/main/windows/main.js
src/renderer/main.js

Closes #181
- Save the bounds of the window when its resized or moved.
- Stored in config.json under "bounds" key (state.saved.bounds)
One oddity: the window is shown at its default centered position until the renderer starts and the state gets loaded, then the window is moved to its saved bounds. 
Setting the bounds when the window is created is possible, but it means loading the state way earlier... (and possibly loading it again once the renderer starts). Any thoughts on acceptable ways to solve this/mitigate the jank at startup?

remember window position

---

src/config.js

Per @dcposch feedback in previous review:
https://github.com/feross/webtorrent-desktop/pull/827/files/aedbc3c32f51813b137e34b5a555a2869c4ccc8f

make WINDOW_MIN_HEIGHT use existing values

---

bin/package.js
package.json
src/.babelrc

Fixes https://github.com/feross/webtorrent-desktop/issues/940
Pros of [`buble`](https://buble.surge.sh/) over `babel`:
- No configuration (a la standard)
- Runs twice as fast, for quicker development
- Converts everything to ES5 (which is likely to be faster than ES6,
but this is untested)
- Easy to swap Babel back in -- low commitment
Cons:
- Less battle-tested than Babel, but recommended by React core
developer so probably not too bad
- No babel plugin support, but we're not using that right now anyway.
Can switch back to babel if we need that later
BEFORE:
$ time npm run build
> webtorrent-desktop@0.16.0 build /Users/feross/code/webtorrent-desktop
> babel --quiet src --out-dir build
npm run build  3.07s user 0.27s system 115% cpu 2.902 total
AFTER:
$ time npm run build
> …

Replace babel with bublé

---

src/config.js
src/main/windows/main.js

I don't think we should dynamically generate the config object -- it
makes it harder to figure out what's going on.

Make config static, not dynamic

---

bin/package.js
package.json

This doesn't add anything new that we need, but it deleted some deprecated features, so let's update.
Changelog: https://github.com/electron-userland/electron-packager/blob/master/NEWS.md#800---2016-09-03

Update electron-packager to v8

---

package.json

Changelog: https://github.com/electron/electron/releases/tag/v1.4.1
(Should fix the Spectron console issue that @dcposch reported.)

Update Electron to 1.4.1

---

package.json
src/main/index.js
src/renderer/controllers/prefs-controller.js
src/renderer/controllers/torrent-controller.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/controllers/update-controller.js
src/renderer/lib/state.js
src/renderer/main.js

- Make State.save() always throttle calls -- since that's the common
case.
- Immediate saves are now the exception, with State.saveImmediate().
- The function is called State.save(), so the dispatch event should be
'stateSave'.

State cleanup, rename, & tweaks

---

src/main/index.js
src/main/ipc.js
src/main/menu.js
src/main/windows/main.js
src/renderer/lib/migrations.js
src/renderer/lib/state.js

Every require() that we do before the users sees UI reduces startup
time.
I used the following code (added to index.js) to log every require()
call in the main process:
```js
var Module = require('module')
var required = {}
Module.prototype.require = function (orig) {
return function (id) {
if (!required[id]) {
required[id] = true
console.log(`${id}   (from ${this.filename})`)
}
return orig.apply(this, arguments)
}
}(Module.prototype.require)
```
From this I was able to learn that lots of modules were being required
that aren't actually used until later.
I also sent this related PR to eliminate another few require()s:
https://github.com/LinusU/node-application-config/pull/4
This increases startup time by 50ms.
We'll probably realize much bigger gains by following this same
procedure for …

startup perf: Reduce require() calls

---

src/main/windows/about.js
src/main/windows/main.js

This gets rid of the light gray to dark gray background color change on
the main window at startup. Makes the window show slightly later, but
it's gray for less time. Doesn't affect overall startup time. Feels
less jank IMO.
From the Electron docs:
> While loading the page, the 'ready-to-show' event will be emitted
when renderer process has done drawing for the first time, showing
window after this event will have no visual flash.

Wait for 'ready-to-show' event before showing window

---

src/renderer/webtorrent.js

This still keeps the peer ID printable as ascii, while adding lots more entropy

Add more peer ID entropy

---

src/renderer/pages/torrent-list-page.js
static/main.css

Hi there!
This replaces the built in progress bar for chrome with the progress bar from material-ui.
This helps make a unified experience across platforms.
Thanks!

use a progress bar from material-ui

---

src/config.js

Fixes: #971
This is a perfect example of putting too many statements into a
try-catch block. My bad. I was trying to keep the code simple, but it
bit us here.
This happens because we were using IS_PRODUCTION, but the order of the
consts at the top are:
const IS_PORTABLE = isPortable()
const IS_PRODUCTION = isProduction()
So we're inside of isPortable() and referring to IS_PRODUCTION before
it's defined. This should have thrown an exception, but it was caught by 
the try-catch block. 
Also, even after moving it out of the try-catch block, it still doesn't throw
an exception because we're transforming to ES5, so the consts are
changed to vars.
Also, standard should have caught this, but there's this bug https://github.com/feross/standard/issues/636 that is preventing
us from enabling the …

Fix Windows Portable App mode

---

src/renderer/pages/torrent-list-page.js

Native apps don't have the "hand" cursor

Don't show pointer cursor on torrent list checkbox

---

src/config.js

With `fs.accessSync`, we check that the folder is readable/writable by us.

Switch fs.statSync to fs.accessSync, which is faster

---

bin/package.js

Create "Portable Settings\Downloads" folder to prevent "Download path
missing" warning, on Windows.

Fix "Download path missing" for Portable App first run

---

.nodemonignore
package.json

Adding configuration files for every tool used will clutter up the repository, especially for a configuration as simple as this.

Remove `.nodemonignore` file.

---

bin/package.js
src/config.js
src/main/index.js

Fixes two portable app bugs, to make the app fully "silent", not just
"portable". This means that not only are all data files stored in the
"Portable Settings" folder, but the app should leave no trace on the
host system.
- Disable Electron's single instance mode so no lock file is created in
"%APPDATA%\Roaming\WebTorrent".
- Put Electron crash files, and other electron files into the "Portable
Settings\Temp" folder instead of "%APPDATA%\Temp".

Make Portable App also a Silent App

---

src/renderer/controllers/media-controller.js

Fixes #984.
Since we are going straight to the player now, a race condition can occur where the media server is not running before spawning the external player.

Delay external player if server is not ready

---

src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/torrent-summary.js
src/renderer/main.js

On paste: Do not handle multiple newline separated torrent ids
- If the user accidentally pastes something that's not a torrent id, then they get one "Invalid torrent Id" error for each line of the text.
- Sure, this removes a "feature", but it's a pretty surprising one. When
I added it, I was being too clever, IMO.
Trim extra spaces off pasted magnet links
- Before this change, using the "Open Torrent Address" dialog to paste a
magnet link would fail with leading or trailing spaces.
- Pasting on the torrent list page has always trimmed. So this PR just
makes it consistent.

Improve paste handling

---

src/renderer/controllers/torrent-list-controller.js

Fixes issue mentioned by @demoneaux https://github.com/feross/webtorrent-desktop/issues/816#issuecomment-250070097.

Go back to list on path missing error

---

src/renderer/pages/create-torrent-page.js
test/test-add-torrent.js

The outline was caused by the wrong class being applied to the button.
Closes #989.

Remove weird outline from “Create Torrent” button.

---

bin/package.js

Electron now offers a "armv7l" build on Linux. Because we were
specifying "all", we were generating an armv7l binary which was being
included in "WebTorrent-vX.X.X-linux.zip" along with the ia32 build,
which explains why it was 90MB+ in the last release.

package: Explicitly specify architectures to build for

---

src/main/windows/main.js

Fixes: https://github.com/feross/webtorrent-desktop/issues/1011

Throttle browser-window 'move' and 'resize' events

---

src/renderer/controllers/playback-controller.js
src/renderer/webtorrent.js

This PR fixes our number 2 top error (142 error reports today
alone):
```
Processes: webtorrent window, platforms: darwin linux win32, versions:
pre-0.12 0.14.0 0.17.0 0.17.1
TypeError: Cannot read property 'files' of null
at getAudioMetadata (.../build/renderer/webtorrent.js:328:21)
at EventEmitter.<anonymous> (.../build/renderer/webtorrent.js:84:74)
at emitThree (events.js:116:13)
at EventEmitter.emit (events.js:194:7)
```
This error is reproducible if you start webtorrent for the first time
and click the WIRED CD torrent. This causes the renderer process to
send a  'wt-get-audio-metadata' before 'wt-start-torrenting' to the
webtorrent process.
You can reproduce it 100% of the time if you force the race condition
to show itself by slowing down the sending of the 'wt-start-torrenting' …

Fix "Cannot read property 'files' of null"

---

src/renderer/pages/player-page.js

Fixes: #1015
It wasn't clear what was causing this error, and I couldn't reproduce
it.
This PR attempts to resolve the issue by just guarding against the
exception.

Attempt to fix "TypeError: Cannot read property 'startPiece' of undefined"

---

src/renderer/controllers/media-controller.js
src/renderer/controllers/playback-controller.js
src/renderer/lib/state.js
src/renderer/lib/telemetry.js

Relates to #906.
Log play attempt for each item in playlist separately, instead of doing it only once on player close. Include information about external playbacks.

Playback telemetry

---

src/main/menu.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/main.js

Add a new Transfers menu to allow pause all and resume all torrents

---

src/main/menu.js

Fix 'About WebTorrent' menu location on Windows

---

CONTRIBUTING.md
README.md
bin/package.js
bin/release-_post.sh
bin/release-_pre.sh
bin/release-major.sh
bin/release-minor.sh
bin/release-patch.sh

The release scripts don't really work, and there are a lot of manual steps that weren't documented. They are now.

Replace release scripts with instructions

---

src/renderer/lib/torrent-player.js

Fixes: https://github.com/feross/webtorrent-desktop/issues/1124
Note FLAC is not actually playable in Electron, by default. But this
will at least offer to open it in VLC or the user's preferred player.

Treat .FLAC as playable audio

---

package.json

This version of Electron is 3 versions of Chromium newer, so there are
lots of performance improvements.
There is one known issue with this update:
https://github.com/electron/electron/issues/8694 which will be fixed in the next version.
But I think we should merge this anyway so that collaborators can try
out the new Chromium and V8 before we do a release with it. We might
find other bugs.

electron@1.6.0

---

src/renderer/main.js

This patch makes webtorrent to do fullscreen (maximize/unmaximize) when pinch to zoom event (two finger zoom in/out gesture) happened on macOS instead probably less meaningful zoom. Have a look [here](https://github.com/dimsemenov/PhotoSwipe/issues/897) for more info about the approach.
To test this, open webtorrent on mac and do two finger zoom on webtorrent window with and without this patch. The intended gesture matches VLC on pinch to zoom action.
I hope you find this useful. Thanks!

Toggle fullscreen on pinch to zoom

---

src/renderer/pages/player-page.js
static/main.css

The width of the video time was making me uncomfortable 😅, so I fixed by having the numbers be tabular and formatting the time with consideration for the total time. 
I was unable to run the integration tests on my 2016 12" Macbook.
I guess using tabular nums could be applied a lot of other places in the app, such as download percentage, file sizes etc.
Before Image:
After image (Added 1h to duration for test purpose):

Use tabular nums and fixed width for no jitter on time

---

package.json
src/main/folder-watcher.js
src/main/index.js
src/main/ipc.js
src/renderer/controllers/folder-watcher-controller.js
src/renderer/lib/state.js
src/renderer/main.js
src/renderer/pages/preferences-page.js

In response to #1149, this feature adds a preference to watch a folder for new `.torrent` files.
When a torrent file is saved on the watched folder it is automatically added to WebTorrent Desktop.
The feature can be enabled / disabled from preferences.

Watch folder

---

src/renderer/pages/player-page.js

New users will usually leave a software when it _apparently_ fails to deliver what it promised. 
I was surprised myself when I got an error on my first try, but as the explorer that I am, I got through.
I recommended this software to two friends ( neither from the tech areas ), and both closed it after they saw the error message. I know it is a small sample, but I believe it represents the reason for a good amount of bounces in Webtorrent Desktop.
Most torrent users already have VLC or other good softwares, and wont event need to install them. Showing "Unable to Play" instead of "Error" makes this amazing functionality more new-user friendly.

"Error" text on missing Codec error changed to "Unable to Play"

---

src/main/external-player.js

This command line option just sets the 'Always on top' setting in VLC.
The player will pop up in the foreground when playing a video from webtorrent without this option.
Having VLC always on top is very annoying when multi tasking.
If the user wants VLC always on top, they can set it in VLC preferences.

Remove 'video-on-top' from VLC player launch options

---

README.md

This adds instructions on how to install with homebrew-cask. I did find [this comment](https://github.com/webtorrent/webtorrent-desktop/issues/884#issuecomment-244575027), but I’ll try to put your mind at ease regarding that.
1. The cask already exists, and has existed for over two years.
2. You don’t need to support it. Most casks are not supported by their maintainers. We have a vast number of contributors that keep them up to date.
If you have any questions regarding the process, feel free to ask (I’m a Homebrew-Cask maintainer). But rest assured **we do not require any effort on your part to keep the cask going**.

README.md: add cask instructions

---

package.json

This should close:
- https://github.com/webtorrent/webtorrent-desktop/issues/1193
- https://github.com/webtorrent/webtorrent-desktop/issues/1202

Update 'chromecasts' dependency to latest version

---

src/renderer/lib/state.js

Reference: issue: webtorrent/webtorrent-desktop#1417
A promise resolve result ended up as an err argument in the callback, causing initialization of application data to fail.

Fix startup problems (fix for #1417)

---

src/renderer/lib/cast.js
src/renderer/webtorrent.js

Support subtitles on Chromecast by creating a new http server for selected subtitles before calling player.play()
Closes #530

Add support for subtitles on Chromecast

---

package.json
src/renderer/controllers/playback-controller.js
src/renderer/lib/torrent-poster.js
src/renderer/pages/player-page.js

Here we can review the update I propose to ensure we always get proper audio metadata.

Borewit dependency/update music metadata

---

package.json
src/renderer/lib/torrent-poster.js
src/renderer/pages/player-page.js

Update from [v2.0.1](https://github.com/Borewit/music-metadata/releases) to [v2.3.2](https://github.com/Borewit/music-metadata/releases).
Release is out for 5 days, no issues reported against it so far.

Update music-metadata dependency

---

src/renderer/pages/player-page.js

- Fixes audio track number not displayed of the total number of is not defined
- Adds the disk (media) number to audio track properties
- Changes the order of audio track properties

Fix audio track number not displayed and adds audio disk (media) number

---

package-lock.json
package.json
src/renderer/controllers/prefs-controller.js
src/renderer/pages/preferences-page.js

Closes #805
Sorry @feross just noticed you're assigned to that issue.. hope this is not duplicated effort :/
- I took out the nested object path logic from `update` because there are not any preferences that use nested objects currently.

save preferences immediately when changed

---

package-lock.json
package.json

Tested on macOS 10.11.6, producing identical `Info.plist` when packaging.
This PR is blocking PR #1484.

Update plist parser (and fix package-lock)

---

bin/open-config.js
package-lock.json
package.json

This won't change anything, just replaced a devDependency. While installing, npm reported a critical vulnerability warning with [open] and which is no longer maintained hence replaced with [opn]
[open]: https://github.com/jjrdn/node-open
[opn]: https://github.com/sindresorhus/opn

fix: replace dependency `open` with `opn`

---

src/renderer/lib/torrent-poster.js

Issue: [#1436](https://github.com/webtorrent/webtorrent-desktop/issues/1436)
This PR fixes a small Type Error where `filterOnExtension` might return an empty array which will be operated by a map and reduce function. This will cause the reduce function to print out the Type Error. The suggested fix is to check for the empty array and return an Error.

Bug Fix Empty Array Reduce

---

bin/extra-lint.js
src/main/index.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/state.js
src/renderer/lib/telemetry.js
src/renderer/lib/torrent-poster.js
src/renderer/main.js
src/renderer/pages/player-page.js

In order to comply with this new standard rule ☺️ 
https://github.com/standard/eslint-config-standard/pull/133

Prefer const over let

---

src/renderer/pages/player-page.js

The minutes field should be zero-padded as long as the playback media is longer than 9 minutes (including hours).
Fixes #1438.

Ensure that the minutes field in playback indicator is zero-padded.

---

package-lock.json
package.json

Changes:
* Improve .m4a (MPEG-4) format information
* Provide bitrate
* Provide MPEG-4 codec (data format) information

Update music-metadata to 3.5.2

---

src/config.js

1 character fix to update the copyright line from `2014-2018` to `2014-2019` 💅 
Here are the two places this value is used: https://github.com/webtorrent/webtorrent-desktop/search?q=APP_COPYRIGHT&unscoped_q=APP_COPYRIGHT
Happy new year everybody 🎉🍾🚀

Update copyright for 2019

---

package-lock.json
package.json
src/renderer/lib/media-extensions.js

1. Update music-metadata to [v3.6.1](https://github.com/Borewit/music-metadata/tree/v3.6.1)
2. Register [DSD](https://en.wikipedia.org/wiki/Direct_Stream_Digital) types as audio media extensions:
1.  Philips DSDIFF (.dff) DSD files
2. Sony .dsf (DSD Stream File) format
This update PR aims to:
1. Keep music-metadata up to date 
2. Recognize [DSD audio](https://en.wikipedia.org/wiki/Direct_Stream_Digital) torrents (& ability to read it's metadata)
In order to successfully pass DSD audio streams to VLC.
It maybe required set MIME-type to make VLC understand the audio format.
As far as I know there are no MIME-type defined for DSDIFF & DSF, at most some unofficial conventions.

Update music metadata

---

src/renderer/main.js

This is a continuation of PR https://github.com/webtorrent/webtorrent-desktop/pull/1443, which appears abandoned. 
Props to @hicom150 for starting that. I would have added commits on top of that, to preserve git history etc, but the underlying branch looks deleted 😕
This PR takes into account the code changes requested by @mathiasvr in https://github.com/webtorrent/webtorrent-desktop/pull/1443#issuecomment-429120108
> I would request the following changes:
> 
> * use keydown instead of keyup, i think instant feedback and repeated events is an improvement.
> * use window.addEventListener instead of document.addEventListener.
> * use e.key instead e.code, currently this PR only works with qwerty keyboard layouts.
All of these have been included. 
👍 This PR has been tested to work locally on …

Add YouTube style hotkeys. Closes #1395

---

src/renderer/lib/migrations.js
src/renderer/lib/sound.js
src/renderer/lib/state.js
src/renderer/main.js
src/renderer/pages/preferences-page.js

This PR is related to the #1067 issue
As the notificaiton sounds seem a bit controversial, I guess the best way to content everybody would be to allow people to chose what they want, hence this little checkbox to toggle the sounds 😃 
Personnally, I'm like @rjmill : sometime I need absolute silence, and sometime I need the notifications.
Anyways, I'm open for feedback 👍

Toggle the sound notifications

---

static/linux/webtorrent-desktop.desktop

If you run `desktop-file-validate` on the desktop file you will get this list of errors
```
desktop-file-validate /usr/share/applications/webtorrent-desktop.desktop                                                         master    
/usr/share/applications/webtorrent-desktop.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
/usr/share/applications/webtorrent-desktop.desktop: error: file contains key "Path" in group "Desktop Action CreateNewTorrent", but keys extending the format should start with "X-"
/usr/share/applications/webtorrent-desktop.desktop: error: file contains key "Path" in group "Desktop Action OpenTorrentFile", but keys extending the format should start with "X-"
/usr/share/applications/webtorrent-desktop.desktop: error: file contains key "Path" in …
```

Fix the desktop file

---

src/main/windows/main.js

This fixes bugginess w/ a duplicated title bar on macOS, as part of the upgrade to Electron 4 (https://github.com/webtorrent/webtorrent-desktop/pull/1590):
----
Docs about this param: https://electronjs.org/docs/api/frameless-window#hiddeninset 
Note about this breaking change introduced in Electron 2.0: https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#browserwindow-1
> <img src="https://user-images.githubusercontent.com/6340841/58850034-90180400-8641-11e9-9f0e-964e6a2aee22.png" width="550px" />

Fix hiddenInset (Mac) titlebar style for electron 4

---

src/main/windows/main.js
src/main/windows/webtorrent.js

-------
This updates the invocations of `.openDevTools()` to match the new `detach` pattern required by Electron 3.0 (described in [Breaking Changes doc](https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#webcontents)):
-------
Tested to work on MacOS 👍

Electron 4: Migrate .openDevTools() for new 'detach' pattern

---

package-lock.json
package.json
src/renderer/pages/player-page.js

- Update music-metadata to version [~~4.1.1~~](https://github.com/Borewit/music-metadata/releases/tag/v4.1.1) [4.2.0](https://github.com/Borewit/music-metadata/releases/tag/v4.2.0)
- Adapt to it's API changes: `format.dataformat` replaced by `format.container` & `format.codec`

Update music-metadata to version 4.2

---

src/main/handlers.js

As described in #1645 `npm run clean` fail in Linux as `rimraf` expects a callback to be defined unless we use the `.sync` method.
This PR fixes this issue.

Fix uninstall handlers in Linux

---

bin/extra-lint.js
package-lock.json
package.json
src/main/index.js
src/main/windows/about.js
src/main/windows/main.js
src/main/windows/webtorrent.js
src/renderer/lib/telemetry.js
src/renderer/pages/player-page.js

~~DO NOT MERGE.~~ Ready to merge!
There seems to be an issue with the media codecs in this version of Electron. Sintel and the WIRED CD do not play back directly in Electron anymore. Instead, VLC is recommended. We need to dig into this problem to figure out if the problem is on our end or on Electron's. If it's Electron, we need to file an issue.

Update to Electron 6

---

src/renderer/controllers/playback-controller.js
src/renderer/lib/playlist.js

This is a small fix to show the file name when streaming content.
As @feross suggested in #1349 changing `mediaUrl` from `https://localhost:port/<file-index>` to `https://localhost:port/<file-index>/<file-name>` fixes the issue.

Pass title metadata in media url

---

src/renderer/components/path-selector.js
src/renderer/pages/preferences-page.js

- Moves path logic to PathSelector component
- Removes `displayValue`, and always shows path instead.
I think it makes sense to remove `displayValue`, because it's only used to display the name of the external player, which is inconsistent with how we display other paths.
Also, the player name is already displayed in a message above the path, so we don't lose that information.

Cleanup preferences page

---

package-lock.json
package.json

Update music-metadata to [v4.3.0](https://github.com/Borewit/music-metadata/releases/tag/v4.3.0), improves decoding of MPEG-4-ADTS/AAC encoded audio tracks.

Update dependency music-metadata to v4.3.0

---

bin/package.js

Although all changes proposed in this PR work perfectly fine, I found some issues while packaging as `electron-packager` removed callback based API.
This commit tries to fix this problem. 😅
Apart from this everything looks good!  💪

Change electron-packager from callback to promises

---

src/renderer/lib/state.js
src/renderer/webtorrent.js

[x] Bug fix
Addresses my review here: https://github.com/webtorrent/webtorrent-desktop/pull/1419#pullrequestreview-285182318

Use promise then() instead of catch() with callbacks

---

package-lock.json
package.json
src/renderer/lib/migrations.js
src/renderer/lib/state.js
test/setup.js

[x] Bug fix
This is the error on Windows that was preventing release of WebTorrent Desktop 0.21.0. https://github.com/webtorrent/webtorrent-desktop/issues/1674#issuecomment-528746939
Is the Local folder read-only? Possible long-term fix is to remove 'application-config' dependency and use `electron.app.getPath('appData')` directly.

Fix "EPERM: operation not permitted, open 'C:\Users\account\AppData\Local

---

package.json

[ ] Bug fix
[x] Other, please explain:
Given that we are currently in `electron@6.0.9` and that in that release `chromium` is included at version `76`, we can tell `buble` to target this and get rid of all the unnecessary transformations and created a more optimized build 💪
Note: `buble` highest target version for chrome is `71` so this is the one included in this PR.

Add buble compiler target chrome version

---

src/renderer/components/path-selector.js

[x] Bug fix
Avoid passing null values from `props.value`
Related to #1702, fixes #1652.
This change is more consistent with the current code, but in the future, we should consider
validating the types instead, since we use already React PropTypes.

Handle null paths in path selector

---

README.md
bin/package.js
package-lock.json
package.json

[ ] Bug fix
Given that we have recently added `electron-installer-debian` it is straightforward to add `electron-installer-redhat` and add rpm file creation support.
It would be nice if someone with Fedora could check if the generated package works as expected 😅
Related:
* #1502 _.rpm package for Fedora, etc_

Add rpm package creation support

---

src/renderer/lib/migrations.js
src/renderer/lib/state.js

**What is the purpose of this pull request?**
**What changes did you make?**
PR #1498 fixed issue #1652 for `downloadPath` and `torrentsFolderPath`, but not for `externalPlayerPath`. I changed the default value to `""`.
I handled existing config files that have `externalPlayerPath = null` by changing this to `""` when loading the config file. It's not a beautiful solution, but otherwise they have to edit it by hand.

Set default externalPlayerPath

---

README.md

[ x] Documentation update
[ ] Bug fix
Show how to install mono to generate the windows installer

mono is needed to create setup.exe

---

src/renderer/pages/torrent-list-page.js

Use `Math.floor` to display the percentage complete for individual files.
Fixes #1713

Floor individual file percentages for display

---

src/renderer/pages/torrent-list-page.js

When starting a torrent that is partially-downloaded, WebTorrent will now report "Verifying" as it verifies the existing data on disk.
If "Verifying" isn't the correct word, let me know. I just used it because it's what the underlying webtorrent library calls it.
Fixes #1586

Report when files are being verified

---

package.json
static/linux/webtorrent-desktop.ejs

[x] Bug fix
Add `--no-sandbox` option to launch scripts (Desktop files) to temporary fix #1703 issue.
Check on different platforms. I've checked successfully in Ubuntu 18.04.3 LTS and Debian 8 Jessie

Add --no-sandbox option to desktop files

---

package-lock.json
package.json

Update music-metadata to [v4.8.0](https://github.com/Borewit/music-metadata/releases/tag/v4.8.0).
No major changes, small [bug fix](https://github.com/Borewit/music-metadata/issues/266) which can occur parsing a FLAC file, which embeds cover art in non standard way.

Update music-metadata to v4.8.0

---

src/main/announcement.js
src/main/menu.js
src/main/updater.js
src/main/windows/main.js
src/main/windows/webtorrent.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/lib/torrent-poster.js
src/renderer/main.js
src/renderer/pages/player-page.js

[ ] Bug fix
[x] Other, please explain:
Fixes type errors, mainly according to new Electron version.

Fix a few type errors

---

package-lock.json
package.json

Update to [music-metadata 4.9.2](https://github.com/Borewit/music-metadata/tree/v4.9.2)
Fix issues that may cause an error parsing an MP4 file.
This not the latest, this should be very stable, I don't foresee any risk updating.

Update music-metadata to 4.9.2

---

README.md

**What is the purpose of this pull request?**
**What changes did you make?**
Looks like Material UI changed the URL to their "Getting Started" Page. The old URL shows a 404 Not Found error message. However, the README.md file in webtorrent-desktop was still referring to the broken link. This PR fixes the broken link to the "Getting Started" page of Material UI in the README.md to go to the installation page of Material UI.
#1734 
- I am not sure if I should have suffixed the URL with a forward-slash or not. The new URL seems to work - with or without a slash. I have chosen not to suffix with forward-slash.
- Without forward-slash suffix: …

Fixed Material UI Getting Started link

---

src/main/dialog.js
src/renderer/components/path-selector.js
src/renderer/controllers/subtitles-controller.js
test/mocks.js

[x] Bug fix
This PR updates dialog functions to use up to date *Sync versions. 
When updating to `electron@7.0.0` dialog with callback functions have been deprecated, so I've updated with the up to date ones.

Fix deprecated dialog callback functions

---

package.json
src/renderer/webtorrent.js

[ ] Bug fix
[x] Other, please explain:
Remove external `deep-equal` dependency in favor of nodejs internal `util.isDeepStrictEqual` one.
Just replace `deep-equal` dependency in favor of nodejs internal `util.isDeepStrictEqual`
Removes an external dependency and uses a faster (~3x) nodejs internal one.

Remove deep-equal dependency

---

package-lock.json
package.json
src/renderer/lib/media-extensions.js
src/renderer/webtorrent.js

Update dependency to [music-metadata v6.1.0](https://github.com/Borewit/music-metadata/releases/tag/v6.1.0)
Changes:
1. Update call to `parseStream` with [IFileInfo](https://github.com/Borewit/strtok3#IFileInfo), to adopt to [music-metadata v6 API](https://github.com/Borewit/music-metadata/releases/tag/v6.0.0)
2. If the parsing of the file (or torrent stream) has completed, send a final update event with metadata.
3. Renamed promise `onMetaData` to `onMetadata`
4. Add additional audio extensions (which mostly helps to determine if torrent is audio torrent):
| extension | Description                                                     |
|-----------|-----------------------------------------------------------------|
| .m2a      | [MPEG-1 Layer 2 Audio …

Update music metadata 6.1.0

---

src/config.js

Last year I manually updated the copyright: https://github.com/webtorrent/webtorrent-desktop/pull/1546. The year before that it was caught by @SimplyAhmazing: https://github.com/webtorrent/webtorrent-desktop/pull/1304. 
But now it's out-of-date again.
This PR sets it to automatically use the current year.
Happy new decade everyone 🥂

Automatically keep the copyright year up-to-date

---

package-lock.json
package.json

Update [v6.3.6](https://github.com/Borewit/music-metadata/releases/tag/v6.3.6).
Minor fixes, low risk.
Can we switch to [Dependabot](https://github.com/dependabot) @feross?
Would be convenient if pending PR's are automatically updated to the latest dependency.

Greenkeeper/music metadata 6.3.6

---

bin/package.js
src/config.js
src/main/index.js
src/main/ipc.js
src/renderer/controllers/media-controller.js
src/renderer/controllers/subtitles-controller.js
src/renderer/controllers/torrent-controller.js
src/renderer/controllers/torrent-list-controller.js
src/renderer/controllers/update-controller.js
src/renderer/lib/torrent-poster.js
src/renderer/main.js
src/renderer/webtorrent.js

[ ] Bug fix
[x] Other, please explain: linting update
I started using object shorthand for properties, that is, I changed `eslint: eslint` to `eslint`.
https://github.com/standard/eslint-config-standard/pull/166
n/a
-----
Compatibility: This syntax is compatible with Node >=4 and Electron >= 0.32 ✅

Use object shorthand for properties

---

bin/darwin-entitlements.plist
bin/package.js
package.json

Fixes: https://github.com/webtorrent/webtorrent-desktop/issues/1675
[ ] Bug fix
This PR adds macOS Notarization. macOS 10.15 Catalina requires apps to be "notarized". Since I just published a new version of WebTorrent since Apple started enforcing this requirement, the app is now blocked on first run. This PR fixes that.
Fixes: https://github.com/webtorrent/webtorrent-desktop/issues/1675

Add macOS Notarization

---

src/renderer/webtorrent.js

Fix issue #1833.
Problems is that the observable used to retrieve the metadata, close to real-time, is passing the inter [MetadataCollector object](https://github.com/Borewit/music-metadata/blob/master/lib/common/MetadataCollector.ts) which implements the metadata interface. Problem is in this scenario, to pass the data from main to browser, the data is serialized. The solution is simple, just pass the metadata only, which does not contain functions. 
I used this function btw to detect functions inside the event data:
```js
function clone(x) {
return JSON.stringify(x, (key, value) => {
if (typeof value === 'function') {
throw new Error('metadata shall not contain functions');
}
return value;
});
}
```
Using something like `clone(metadata)` to understand what the issue was.
I was in doubt …

Fix audio metadata not being displayed

---

src/main/squirrel-win32.js

[x] Bug fix
Refactor windows installer event handler.
This PR fixes #1745 where windows installer does not create start menu and desktop shortcuts.
I tested it in Windows 10 but it would be nice it someone could help to test in other windows versions.

Fix windows installer event handler

---

src/renderer/main.js

[x] Bug fix
A simple copy of line from the previous function
Fixes #1839 

Fix #1839: Prevent keypress events on user input elements

---

src/main/external-player.js

https://github.com/webtorrent/webtorrent-desktop/blob/eb5a291c8b9cbfae96f306e153387e720a7baa72/src/renderer/lib/migrations.js#L219 cause external player to be a empty string instead of a null one
[X] Bug fix
VLC does not start
Fix #1807

Fix #1807 (VLC does not start)

---

package-lock.json
package.json

Update dependency [music-metadata](https://github.com/Borewit/music-metadata) to [version v7.0.2](https://github.com/Borewit/music-metadata/releases/tag/v7.0.2) fixing a possible exception thrown while parsing WAV file.

Update music-metadata to version 7.0.2

---

src/main/windows/about.js
src/main/windows/main.js
src/main/windows/webtorrent.js

Reference: https://github.com/webtorrent/webtorrent-desktop/pull/1720#issuecomment-722011487
I actually think we want backgroundThrottling: false so our timers and intervals aren't throttled when the app is backgrounded.
[x] Bug fix
Disable background throttling. See https://www.electronjs.org/docs/api/browser-window
None

Disable background throttling

---

package-lock.json
package.json

[ ] Bug fix
Inspired by @hicom150's PR https://github.com/webtorrent/webtorrent-desktop/pull/1695, I swapped out `buble` for `babel`.
This way we can target just the JSX transformation. We don't use any other cutting edge JS features that require compilation, nor should we in the future.

Use babel instead of buble

---

package-lock.json
package.json

[ ] Bug fix
[x] Other, please explain: Update dep
Upgrade to Electron 11
Possibly addresses #1894
I'd like to start testing out Electron 11 on `master` so we can see if there's any deprecated APIs that we need to upgrade, etc. Then when Electron 11 is stable, we can do another release of the app :)
UPDATE: Electron 11 stable was just released.

Upgrade to Electron 11

---

static/linux/webtorrent-desktop.ejs

**What is the purpose of this pull request?**
Bug fix
WM_CLASS of the application is `webtorrent` or `WebTorrent`:
```bash
$ xprop WM_CLASS
WM_CLASS(STRING) = "webtorrent", "WebTorrent"
```
But in .desktop file is set `webtorrent-desktop`:
```bash
$ cat webtorrent-desktop.desktop | grep WM
StartupWMClass=webtorrent-desktop
```
This causes the desktop environment to not correctly connect the running instance of the application with a desktop file. This leads to not using system icon theme for the icon of running application.
**Now:**
**Expected:**
<hr>
The `Version` entry in the .desktop file is currently set to the application version:
```bash
cat webtorrent-desktop.desktop | grep Ver
Version=0.24.0
```
But according to the …

Fix linux .desktop file

---

src/renderer/pages/player-page.js
static/main.css

Now we're able to see information such as download progress, file size, download speed, ETA and number of peers on the cast screen. 
The displayed information refers to the **currently playing file** only. Many torrents are composed of a single file, but some torrents are composed of several playable files. Showing information of the whole torrent (all files) would confuse the user, I think.
Any thoughts?
How it looks:
Closes #1070

Display download info on cast screen

---

package.json

I want to bump the `package-lock.json` file to use the v2 format.

chore: Set node 16 and npm 7 as minimum versions

---

src/main/index.js
src/main/menu.js

[x] Bug fix
- Init menu before main window.
- Always return an object from `getMenuItem`.
#1315
I wasn't able to reproduce the bug and I'm currently working on OSX.
I might be able to get a Windows setup later to try to reproduce and verify the fix.
It doesn't seem possible for the main window events to trigger callbacks before `onReady()` finishes executing right?
In case I'm missing something about Electron inner workings `menu.init()` is called first now.
Then we ensure `getMenuItem()` …

Fix cannot set property 'enabled' of undefined

---

src/renderer/components/unsupported-media-modal.js

May help with users who are man-in-the-middled and redirected to malicious websites.
See: https://github.com/webtorrent/webtorrent-desktop/issues/1908

fix: Link to VLC using HTTPS

---

bin/package.js

[ ] Bug fix
Add `armv7l` arch support.
Given that `electron-packager` can build for `armv7l` it is just as easy as enabling it to support devices like `Raspberry Pi 3`
and `Raspberry Pi 4` when running in a 32bit mode 😉
https://github.com/webtorrent/webtorrent-desktop/issues/1857

Add armv7l arch support

---

.github/workflows/package.yml

[ ] Bug fix
Add package Github Action. With this action that can be **manually triggered** via `Actions` menu, Linux, MacOS and Windows build will be launched and `linux.zip`, `macos.zip` and `windows.zip` artifacts will be generated.
It is important to note that MacOS and Windows installers are currently **not signed**, so we will have to add this in next steps 😅. I see this PR as the first step towards package build automation 😉
https://github.com/webtorrent/webtorrent-desktop/issues/1849

build: add package Github Action

---

src/renderer/controllers/torrent-list-controller.js

[X] Bug fix
- Adds a condition to go back to the torrent list when the user clicks on any of the `Remove all torrrents` buttons while the player is open
Closes #1936
- The steps to reproduce the bug are in #1936
- Basically, the user wants to delete all torrents while playing one of them. Two possible solutions are:
1. Keep the user from deleting torrents from the player screen
2. Force the user to go back to the torrent list and then delete them
This PR chooses the second option, but any …

fix: resume torrents after deletion

---

src/main/ipc.js

Until now, media keys didn't work when playing a file in VLC (at least on Linux), because they were already taken by WebTorrent. This PR fixes that.

Release media keys when opening external player

---

src/renderer/pages/player-page.js

[X] Bug fix
Set a tiny ghost image on media player progression drag event
#1892 

Fix ghost image showing on media player drag

---

src/renderer/lib/migrations.js

Previously, they were only installed when the preference was changed. This caused the handlers to point to non-existing files after updates occurred and older versions were removed by Squirrel.
Closes #791, #911.

Ensure that default file/protocol handlers are re-installed after updating.

---

README.md
src/renderer/lib/state.js

A playback rate != 1 causes `shouldHidePlayerControls` to erroneously return `false`.
[X] Bug fix
Removed erroneous check in `shouldHidePlayerControls`
[Issue #2501](https://github.com/webtorrent/webtorrent-desktop/issues/2105)

fix: remove erroneous playbackRate check

---

src/renderer/lib/cast.js

[x] Bug fix
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

package-lock.json
package.json
src/main/windows/main.js
static/main.css

[x] Bug fix
Event format seems to have changed, so don't use `event.sender`, but `main.win` in `main/windows/main.js`
Supersedes https://github.com/webtorrent/webtorrent-desktop/pull/2385

Electron 27 update + fix
