main/index.css, main/index.js, main/views/player.js, main/views/torrent-list.js
=> Add button to delete torrents

main/config.js, main/index.js, main/menu.js, main/windows.js
This also captures the true start time since it runs before any
require() calls, so the time to require() will be taken into account.
=> move config.startTime to app.startTime

main/ipc.js
=> Fix IPC calls after PR #4

renderer/index.css, renderer/views/header.js, renderer/views/player.js
- make bottom bar match header bar color
- enlarge cursor and loading bar on hover
- remove extraneous .bottom-bar class
=> Nicer player controls

package.json, renderer/views/app.js, renderer/views/header.js, renderer/views/player.js, renderer/views/torrent-list.js
This is a test branch to show what working with https://github.com/substack/hyperx would like.
Also under discussion is using https://github.com/Raynos/main-loop to optimize virtual dom updates.
=> try hyperx

main/ipc.js, main/menu.js, renderer/index.css, renderer/index.js, renderer/views/player.js, renderer/views/torrent-list.js
=> Cast buttons and fullscreen in player controls

main/menu.js, renderer/index.js
=> menu: new "Add Fake Airplay" and "Add Fake Chromecast" items

main/windows.js, renderer/index.js
If the app is already fullscreen when it is loaded, set
state.view.isFullScreen to the correct state.
=> Start in correct full screen state

package.json, renderer/index.js, renderer/views/header.js, renderer/views/player.js, renderer/views/torrent-list.js
This is more consistent with the rest of standard style, and if this was JSX it would be enforced by the tool.
=> Use single quotes in hyperx

main/menu.js, renderer/index.js, renderer/state.js
- move renderer state into new file
- lots of misc cleanup
=> Client cleanup

renderer/index.css, renderer/index.js, renderer/views/header.js
For some reason this took me a long time to figure out.
=> hide header on video after mouse idle

renderer/index.css, renderer/views/torrent-list.js
=> Unsquash the UI when window is small

renderer/index.js
Two small fixes to bugs introduced in #56. Sorry I didn't catch them during review.
=> fix bugs from #56

main/ipc.js, renderer/index.css, renderer/index.js, renderer/views/torrent-list.js
DL button doesn't do anything yet but looks nice :p
=> Add download button, improve CSS

renderer/index.js
<del>**NOTE**: I can't check now if I messed something up now -- I'm not at home. If you're meant to merge this PR, please consider testing the application *or* just wait few hours</del>
=> Make spacebar trigger play/pause event

renderer/index.css, renderer/index.html, renderer/index.js
On the off chance that loading is taking a while, this PR adds a nice loading spinner. Also makes the script call async which seemed to speed up time to first paint for me. For fun I also added a quick fade in css animation to the app after loading is done, and to new torrents. Up to collaborators if it's worth keeping or tweaking or ditching.
=> add loading state, ui tweaks

renderer/index.js
os.homedir() handles cross-platform complexities for us.
=> Cross-platform home directory detection

renderer/index.css, renderer/views/torrent-list.js
=> add empty list state

main/menu.js
@giuscri if you want to check it works for you too
=> hide menu bar in fullscreen, fix #51

renderer/index.css, renderer/index.js, renderer/views/app.js, renderer/views/header.js, renderer/views/player.js
=> Video controls: never hide when paused

package.json, renderer/index.css
Essentially comes down to this commit to `drag-drop`: feross/drag-drop@d65c46d
=> Fix up drag-drop

renderer/index.css, renderer/index.js, renderer/state.js, renderer/views/app.js, renderer/views/header.js
=> Fix scroll bar going under header bar

main/windows.js, renderer/index.js
=> dispatch a pause event before hiding window on darwin

renderer/index.js
Also, airplay/chromecast: remove unneeded startServer() calls
=> filter file formats that <video> tag definitely can't play

main/ipc.js, main/menu.js, renderer/index.css, renderer/index.js, renderer/views/app.js, renderer/views/header.js, renderer/views/open-torrent-address-modal.js
=> Add Torrent Link modal

main/menu.js
=> fix fullscreen / float on top menu item exception

renderer/index.css, renderer/views/torrent-list.js
=> File details

README.md
Playing around with a https://github.com/sindresorhus/awesome style readme header since I noticed @feross trying to fancy it up with the new logo.
Check out what it looks like at https://github.com/feross/webtorrent-app/tree/readme-alt#readme.
=> fancy readme title

main/ipc.js, renderer/index.css, renderer/index.js, renderer/lib/torrent-player.js, renderer/state.js, renderer/views/player.js, renderer/views/torrent-list.js
Show file list, open folder containing downloaded files, open individual files, play/pause individual videos.
=> Torrent details

renderer/index.css, renderer/index.js, renderer/lib/cast.js, renderer/state.js, renderer/views/app.js, renderer/views/player.js
=> Chromecast video controls

renderer/index.css, renderer/index.js, renderer/state.js, renderer/views/app.js
=> Error popover, no more alert()s

bin/package.js
Before, the plist update code wouldn't run when building for all platforms. Fixed that and refactored the build script a bit.
=> Cleanup build script; Run plist update function for all builds

main/register-protocol-handler.js
=> Register .torrent file hander on Windows

renderer/index.css, renderer/lib/cast.js, renderer/views/player.js
=> Airplay support. Nicer looking cast screen

renderer/index.js
Fixes the add torrent functionality:
* Add files by drag-drop
* Add files via the open dialog
* Add files by copy-paste
Also handles the case where you add a duplicate torrent more gracefully.
=> Fix startTorrenting

main/index.js
=> Prevent multiple instances of the app from running at the same time

main/register-handlers.js
this will complement your work to complete #116
=> add icon for linux desktop file

main/ipc.js, main/windows.js, renderer/index.js, renderer/state.js
=> Fix #176: close window on OSX

renderer/index.css, renderer/index.js, renderer/lib/errors.js, renderer/views/header.js, renderer/views/torrent-list.js
=> Add tooltips

renderer/index.js, renderer/lib/torrent-poster.js
...as a fallback, if no the torrent doesn't contain any video files
=> Use largest image in torrent as the poster

renderer/index.css, renderer/index.js, renderer/lib/cast.js, renderer/lib/torrent-player.js, renderer/state.js, renderer/views/app.js, renderer/views/player.js, renderer/views/torrent-list.js
=> WebTorrent can now play audio

package.json, renderer/index.css, renderer/index.js, renderer/views/player.js
=> Audio metadata

README.md
=> update readme with link to releases

renderer/index.css
fixes #211 
works as expected in other states (fullscreen, idle, index). easy one line fix. :tophat: :rabbit2:
=> fix invisible header bug

README.md, package.json
Also fixes the package arg in one of the npm scripts.
Preview readme changes: https://github.com/feross/webtorrent-app/tree/version#readme
=> Add version badge, update release info

main/handlers.js, main/index.js, main/ipc.js, main/menu.js, renderer/index.js, static/webtorrent.desktop
This PR solves #116 
To implement this the following changes were made
* parameters are not longer torrentId only, handle that with processArgv function
* expose missing menu event invocation (showCreateTorrent)
* add Actions section in .desktop
* fix .desktop/register handler to be used in development mode
Cleanup from PR #194
Thanks @ungoldman for the branch management tip
=> Add unity launcher icons

main/shortcuts.js, renderer/index.js, renderer/lib/cast.js, renderer/views/player.js
* add volume management in local player, chromecast and airplay
* controlled by shortcuts (CtrlOrCmd+Up, CtrlOrCmd+Down)
* test chromecast and airplay
* airplay: could not find a way to get volume in poll cast status, it writes state value in setter by now 
* UI control and status (maybe a HUD like in VLC)
Cleanup from PR #185
=> Add volume management

config.js, main/windows.js, renderer/index.js, renderer/state.js
Also fix a bug: fix relative paths to the default torrents.
=> Add (BETA) to window title

renderer/index.css, renderer/index.html, renderer/index.js, renderer/lib/cast.js, renderer/state.js, renderer/views/torrent-list.js
Lazy load the WebTorrent, Chromecast, and Airplay modules
=> Speed up init() by >= 2x

main/ipc.js, main/windows.js, renderer/index.js
This works great on my slow Macbook 12”, so I assume it will work
without lag on most other people’s computers.
=> Fix OS X flash of white

renderer/index.js, renderer/views/torrent-list.js
=> add context menu with share/save actions

renderer/index.js, renderer/state.js, renderer/util.js, renderer/views/player.js, renderer/views/torrent-list.js
Fixes bug where posters and torrent files can’t be found in the built
app.
=> Resolve posterURL and torrentPath at runtime

renderer/index.js, renderer/lib/dispatcher.js, renderer/views/header.js, renderer/views/open-torrent-address-modal.js, renderer/views/player.js, renderer/views/torrent-list.js
Stop virtualdom from swapping out every event handler on every update
=> Memoize button click handlers

renderer/index.css, renderer/index.js, renderer/lib/dispatcher.js, renderer/state.js, renderer/views/player.js
=> Use currently playing file for window title & loading bar

main/auto-updater.js, package.json, renderer/index.css, renderer/index.js, renderer/state.js, renderer/views/app.js, renderer/views/update-available-modal.js
=> Linux update notifications

renderer/index.css, renderer/index.js, renderer/state.js, renderer/views/player.js
=> Show spinner when audio/video is stalled

renderer/index.js, renderer/lib/location-history.js, renderer/state.js, renderer/views/player.js
=> Save audio metadata, after extraction

renderer/index.js
Keep track of the most recent file modtimes at which we verified that the torrent piece hashes all match.
Requires https://github.com/feross/webtorrent/pull/715
=> Don't re-verify unchanged files

main/menu.js, main/tray.js, renderer/index.css, renderer/index.js, renderer/views/app.js, renderer/views/create-torrent-modal.js
Fixes https://github.com/feross/webtorrent-desktop/issues/254
=> Seed in place, don't copy to /tmp

renderer/index.js, renderer/lib/cast.js
@dcposch @feross: In preparation for DLNA support, the 3 way if/else location===device was a little messy, so I gave it a chance and tried to refactor the cast.js file resulting in this PR.
I don't have a chromecast device and my airplay emulator software is not very good, so i need to verify everything is in order.
I think this can be good base to extend to other external devices (an external player?) and protocols (Miracast? WiDi?)
I tried to keep the interface intact i only changed the openChromecast and openAirplay with an open(<device>), only affected the UI invocation
Also, a code review is always welcome.
=> Review and testing required!: refactor cast module

package.json, renderer/index.css, renderer/index.js, renderer/lib/cast.js, renderer/views/player.js
This PR adds DLNA support, fixing #186
=> Add DLNA support

main/menu.js, main/windows.js, renderer/webtorrent.html
=> Developers menu button to show dev tools

renderer/views/player.js
=> Use Chromecast connected icon when applicable

main/menu.js, main/windows.js, renderer/webtorrent.html
Also, add shortcut for opening webtorrent inspector
=> Prevent killing the WebTorrent process

main/index.js
=> Ignore OS X -psn_xxxx command line argument

renderer/index.js, renderer/lib/cast.js, renderer/state.js, renderer/views/torrent-list.js
* No more pause icon in the file list
* Reset state.playng completely after each play
* Fixes #318: false "cannot add dupe torrent" error
=> Fix player flakiness

main/menu.js
=> Add File > Quit for Linux users with broken system trays

main/ipc.js, main/menu.js, renderer/index.js, renderer/lib/dispatcher.js, renderer/lib/location-history.js, renderer/lib/torrent-player.js, renderer/views/torrent-list.js, renderer/webtorrent.js
+ lots of other bug fixes
Getting ready to ship!
=> Fix playback bug: ensure openPlayer() always calls its callback

renderer/index.css
=> Torrent list title: Show more of the title

crash-reporter.js, main/index.js, renderer/index.css, renderer/index.js, renderer/webtorrent.js
=> Cast screen background: cover, don't tile

renderer/index.css, renderer/index.js, renderer/views/player.js
i am not a great designer but i think its not too ugly... and it works
=> Add volume controls

renderer/views/player.js
Hello, just a quick PR so we can mute/unmute the volume with the volume icon :)
=> add mute/unmute with the volume icon

bin/package.js
Some people are having trouble installing the app in 32 bit Linux, e.g. issue #335 
Don't know about other OS, though
=> 32 bit build for Linux

package.json
=> Use latest webtorrent

bin/package.js, config.js, renderer/index.js, renderer/lib/sound.js
The first time a sound file is played, the Audio object is cached.
5s after startup, all sound files are automatically preloaded.
=> Preload sound files for instant playback

renderer/views/open-torrent-address-modal.js
=> Fix text field focus after repeated open

bin/package.js, package.json
This PR complements #335 and finishes #369
=> Package 32bits and 64bits linux versions in zip and deb formats

bin/package.js
Now we use a function closure to capture the `destArch` variable so the
for loop can't change it.
=> Linux build: Fix incorrect log output

renderer/state.js
=> Use Electron API to get 'Downloads' folder

main/tray.js, main/windows.js
* Stop video or audio when you click Hide from the tray menu
* Don't minimize to tray on Linux systems that don't support it
=> Fix two tray icon bugs

renderer/index.js
=> Block power save (suspend) while casting

package.json, renderer/index.css, renderer/index.js, renderer/views/player.js
No subtitles
add new with click if no subtitles available
Subtitles available
once a subtitle is available, add more subtitles with Ctrl+[CC] click
Subtitles enabled and selected
on [CC] click, show available subtitles
Subtitles menu
* use [languagedetect](https://www.npmjs.com/package/languagedetect) (no deps) to detect subtitle language
=> Add multiple subtitles support

renderer/index.css, renderer/views/open-torrent-address-modal.js, renderer/views/torrent-list.js
Gets us a bit closer to the Material Design style guide
https://www.google.com/design/spec/components/buttons.html#
=> Button styles

main/ipc.js, renderer/index.js
=> Center video on current monitor

bin/package.js, package.json, renderer/webtorrent.js
- fix exception in webtorrent process
- fixes for cross-zip@2
- use electron-winstaller@2.3.0 instead of feross fork
=> Small fixes

bin/check-deps.js, bin/list-deps.sh, package.json
Makes sure something like #451 can't happen again
=> Check for missing or unused dependencies

main/ipc.js, main/vlc.js, package.json, renderer/index.css, renderer/index.js, renderer/lib/torrent-player.js, renderer/views/app.js, renderer/views/player.js, renderer/views/unsupported-media-modal.js
**With VLC present**
**Without VLC**
=> Play unsupported files in VLC

renderer/lib/sound.js
except for delete -- which this pr just makes consistent
=> Reduce sfx volume

main/menu.js
=> Allow to torrent a single file

package.json
My fixes were merged upstream -- no need to depend on my fork anymore.
=> application-config@^0.2.1

bin/package.js, renderer/about.html
=> About WebTorrent: Show `webtorrent` library version

renderer/lib/torrent-player.js, renderer/views/create-torrent-page.js
=> Fix incorrect path when for single-file torrents

package.json
No new features or breaking changes that affect us.
=> electron-prebuilt@1.0.1

main/windows.js, renderer/index.css
=> Fix for overflowing captions icon

main/menu.js
=> push/unshift menu items from submenu in linux/windows

main/ipc.js, main/menu.js, renderer/index.js
(If the download is inside the Downloads folder.)
=> OS X: Bounce the Downloads stack when download completes

renderer/views/player.js
Increase/Decrease Sound with mouse wheel on video hover
=> Increase/Decrease Sound with mouse wheel on video hover

main/handlers.js
When the user is running the development version of the app on Windows, it's not enough to use `process.execPath` to register the magnet link and file handlers. Since the executable being registered is `electron.exe` we also need to add an argument that points to the app folder.
This also affects users of the npm package i.e. `npm install webtorrent-desktop -g` :)
Closes #497.
=> Windows: Fix handler registration for development version of app

main/index.js
=> Wait for the app ready event before creating windows

main/index.js, package.json, renderer/index.js
When manually adding subtitle track(s), always switch to a new track
Also fix a bug I added in 63e7aa8c7f2708b9eb6957267284e5f19073fd96
=> Simplify subtitles code

package.json, renderer/index.js, renderer/webtorrent.js
=> Clean up addSubtitles

package.json
=> nobin-debian-installer@0.0.10

LICENSE, README.md, config.js, package.json
What is WebTorrent, LLC?
WebTorrent, LLC is the legal entity that runs the WebTorrent project.
WebTorrent is still, and always will be, non-profit, open source, free
software.
There are no plans to make a profit from WebTorrent.
=> WebTorrent, LLC

renderer/index.js
=> Add support for pasting a `instant.io` link.

renderer/index.css, renderer/views/player.js
=> Add support for video progress time in player controls.

renderer/index.js
=> Fix Uncaught TypeError: Cannot read property 'update' of undefined

renderer/views/player.js
=> Cleanup unsupported codec detection

renderer/index.css, renderer/index.js, renderer/state.js, renderer/views/player.js, renderer/views/torrent-list.js
Fixes #405 
Also cleaned up the styling on the list of files when you expand a torrent
=> Save video position

renderer/views/player.js
=> Cleanup unsupported codec detection (pt 2)

main/index.js, main/menu.js, main/shortcuts.js, package.json
=> Simplify shortcuts. Go Back menu item

renderer/views/create-torrent-page.js, renderer/views/player.js
=> Show error when drag-dropping hidden files

main/index.js, main/menu.js, renderer/index.js, renderer/webtorrent.js
=> Allow dropping files on dock icon

renderer/views/home.js
=> Fix issue with file sorting.

renderer/main.js
See https://github.com/feross/webtorrent-desktop/pull/593#issuecomment-222897517
=> Error on duplicate add (fixes to PR #593)

renderer/main.css
=> Fix subtitle controls radio button size

renderer/lib/torrent-poster.js
Fix for a little bug we ran into while demoing for someone at Decentralized Web Summit
=> Make posters from jpeg files

renderer/main.js, renderer/views/open-torrent-address-modal.js, renderer/views/update-available-modal.js
I noticed that the modals had some minor inconsistencies. Do these changes seem alright?
=> fix modal inconsistencies

main/ipc.js, main/shell.js, renderer/main.js
Support for moving torrent data to trash, and context menu items as proposed in #560.
=> Remove torrent data support

main/windows/main.js
=> Prevent playback continues after minimize

bin/package.js
Hi,
dependencies for the deb package, tested with debian jessie
=> add debian jessie dependencies

main/menu.js, renderer/controllers/playback-controller.js, renderer/controllers/torrent-list-controller.js, renderer/main.js, renderer/webtorrent.js
Bugfixes for `dc/refactor` branch (#693):
- `Invalid torrent identifier` error when adding new torrent
- `Step Forward` and `Step Backward` commands not working
=> Fixes for dc/refactor branch

README.md, main/index.js, main/menu.js, renderer/controllers/media-controller.js, renderer/controllers/playback-controller.js, renderer/controllers/prefs-controller.js, renderer/controllers/subtitles-controller.js, renderer/controllers/torrent-list-controller.js, renderer/controllers/update-controller.js, renderer/lib/cast.js, renderer/lib/state.js, renderer/lib/telemetry.js, renderer/lib/torrent-player.js, renderer/lib/torrent-summary.js, renderer/main.js, renderer/views/app.js, renderer/views/create-torrent.js, renderer/views/player.js, renderer/views/torrent-list.js, renderer/webtorrent.js
* Simplify startup
* Split out controllers that handle dispatch(...) events. So far we have a MediaController (for local media playback events) and UpdateController (for the new version available UI).
The goal is to make `main.js` small and readable. Currently it's a 1600 line file that does all kinds of things.
=> Refactor main.js

renderer/controllers/torrent-list-controller.js
=> Remove torrent file and poster

renderer/controllers/torrent-list-controller.js
=> onError -> error

renderer/controllers/torrent-list-controller.js, renderer/lib/torrent-summary.js
=> Remove torrent data (single file / folder)

renderer/controllers/playback-controller.js, renderer/controllers/torrent-controller.js, renderer/lib/torrent-player.js, renderer/main.js, renderer/views/torrent-list.js
* Move all the torrent event handlers to their own file `torrent-controller.js`
* Move all the file extension checking to the same place
=> Refactor main.js: down to 450 lines

renderer/views/torrent-list.js
Adds the estimated time to download completion of the torrent (Hours Minutes Seconds) in the torrent's status.
=> Display torrent ETA in list item

README.md, bin/package.js, package.json, src/main/dialog.js, src/main/dock.js, src/main/handlers.js, src/main/index.js, src/main/menu.js, src/main/tray.js, src/main/windows/main.js, src/renderer/lib/state.js, src/renderer/main.js
OS X is no longer the marketing name. It's technically macOS, but I'm using Mac in the website marketing since that's what I think users will expect.
=> OS X -> Mac

package.json
Electron changelog: https://github.com/electron/electron/releases/tag/v1.3.1
The only bugfix that potentially affects us is:
- Window position doesn't restore correctly
None of the new features is relevant to us.
=> electron-prebuilt@1.3.1

src/main/index.js, src/main/user-tasks.js
=> Add User Tasks for Windows.

package.json
Changelog: https://github.com/electron/electron/releases/tag/v1.3.2
Nothing in the changelog fixes known WebTorrent Desktop issues.
=> electron-prebuilt@1.3.2

src/renderer/views/torrent-list.js
=> Fix "Cannot read property 'numPiecesPresent' of undefined"

CONTRIBUTING.md
=> Add Smoke Tests to CONTRIBUTING.md

src/renderer/views/create-torrent.js
=> Create Torrent: make trackers editable again

package.json, src/renderer/views/app.js, src/renderer/views/create-torrent.js, src/renderer/views/player.js, src/renderer/views/torrent-list.js
The only thing we have to change is to self-close tags that don't
contain anything. This wasn't even an explicit change in standard. It
was already a rule, but I think it wasn't getting enforced very well
until a bugfix.
=> update to standard v8

src/main/windows/main.js, src/renderer/main.js
Fixes: https://github.com/feross/webtorrent-desktop/issues/786
=> Only use setContentBounds for player view

src/main/external-player.js, src/renderer/controllers/playback-controller.js, src/renderer/controllers/subtitles-controller.js, src/renderer/lib/migrations.js, src/renderer/lib/telemetry.js
=> A bunch of small fixes

src/renderer/lib/telemetry.js
=> Telemetry: redact stacktraces

src/renderer/lib/telemetry.js
=> Telemetry: log app version

.gitignore, bin/cmd.js, bin/package.js, package.json
=> Switch from electron-prebuilt to electron

src/renderer/lib/torrent-player.js
=> Audio: support .m4a

static/main.css
Almost every other app in Windows uses 'Segoe UI' and it'd be nice if WebTorrent Desktop uses the same.
=> Add 'Segoe UI'

src/renderer/pages/PlayerPage.js
When playing audio files the poster was not displayed.
=> fix player poster image css bug

src/renderer/controllers/torrent-controller.js
=> Prevent notification sound during playback

src/renderer/pages/PlayerPage.js
=> Don't render player controls when using external player

package.json, src/renderer/webtorrent.js
It's not needed and less random than the built-in crypto lib
=> Remove 'hat' dependency

src/main/index.js, src/renderer/lib/telemetry.js, src/renderer/main.js
=> Telemetry: log version in errors

package.json, src/renderer/components/ShowMore.js, src/renderer/pages/CreateTorrentPage.js, src/renderer/pages/PreferencesPage.js, static/main.css
* Fixes the Create Torrent screen:
* Wires up the "Make WebTorrent your default torrent app" button
* Fixes a bug in the way we were using depcheck. Only checks `src` and `bin` now, not `build` or `dist`.
@feross
=> Finish Material UI

src/renderer/lib/migrations.js, src/renderer/pages/torrent-list-page.js, static/main.css
All those gradients and brightness filters toggling on and off were getting annoying
=> Torrent list design

src/renderer/controllers/torrent-controller.js, src/renderer/controllers/torrent-list-controller.js, src/renderer/lib/cast.js, src/renderer/webtorrent.js
From telemetry.
@feross @mathiasvr
=> Fix some of the common errors

src/renderer/controllers/torrent-controller.js
This was changed incorrectly in 2a1e987.
=> Fix notification click not working.

src/renderer/components/show-more.js
=> Use raised button for inline button

src/renderer/lib/migrations.js, src/renderer/webtorrent.js
=> Fix a sad, sad bug that resulted in 100+MB config.json

src/main/index.js
As mentioned in
https://github.com/feross/webtorrent-desktop/pull/827#discussion_r799219
59
We should load the state outside the app.on('ready') handler so there's
a chance it's ready by the time 'ready' fires.
This improves startup time by roughly 50ms on my Macbook 12".
=> main: Start loading state before app is ready

package.json, src/config.js
Hi,
I replaced some of the code with the package arch, which was exactly the same 😄
=> use arch to determine OS_SYSARCH

src/renderer/main.js
=> avoid saving window bounds when on player

src/renderer/pages/torrent-list-page.js
React converts to string and adds 'px' automatically
=> Pixel values should use numbers, not strings

bin/package.js
See inline comment for explanation.
=> Disable Windows delta updates

package.json
Changelog: https://github.com/electron/electron/releases/tag/v1.4.2
=> Update Electron to 1.4.2

src/renderer/pages/player-page.js
Removed comma and added space after download speed.
=> #1039: Formatting fixed.

src/renderer/controllers/torrent-list-controller.js
=> Disallow saving torrent file until it is generated

src/renderer/components/modal-ok-cancel.js
=> Auto-focus modal 'OK' button to allow keypress

src/renderer/main.js
=> Add textarea to list of html tags that skip document-wide onPaste

src/main/menu.js
Probably improves the accessibility situation a little bit: #439
=> Add 'Start Speaking' and 'Stop Speaking' menu item (Mac)

src/config.js
Was reading the code and looking for other things but this stuck out to me as I was passing by...
=> Update copyright a year later

src/renderer/pages/player-page.js
Stupid simple PR to exit fullscreen after movie ends.
closes #1248
=> Exit fullscreen after movie ends

src/renderer/pages/torrent-list-page.js
=> Add missing key to torrent status element

package.json, src/renderer/controllers/torrent-list-controller.js
=> Bugfix 1314

package.json, src/renderer/pages/player-page.js
Multiplicity of common.label & common.catalog-number number changed.
Added possibility to visualize multiple labels & catalog-number in pairs.
=> Update dependency music-metadata v1.0.0

src/renderer/pages/player-page.js
=> Fix code style

README.md
<a href="https://github.com/webtorrent/webtorrent-desktop/releases"><img src="https://img.shields.io/github/downloads/webtorrent/webtorrent-desktop/total.svg" alt="github release downloads"></a>
=> add github download count badge

src/renderer/lib/media-extensions.js, src/renderer/lib/torrent-player.js, src/renderer/lib/torrent-poster.js
Share declaration of media-file-extension per media category (audio, video & image).
Add additional file extensions:
* m4b (MPEG-4 Audio Book File), required for #1452
* wv (WavPack)
=> Reuse media extensions

package-lock.json, static/main.css
This appeared to have been removed accidentally when other parts of the CSS was refactored.
=> Add back loading spinner for player page.

README.md
As there is no too much information in the readme.md in how is this made, I think put a link of Electron and React to have an idea of the technologies used here is a good starter.
=> Recommended readings to start working in the app.

src/renderer/pages/preferences-page.js
Changed function name handlesoundNotificationsChange for handleSoundNotificationsChange
=> Changed function name handlesoundNotificationsChange for handleSoundNotificationsChange

CHANGELOG.md
This is a list of changes in the form of PRs that have been merged since `v0.20`.
In addition, many changes and PRs have been made regarding: dependency updates, code refactoring, and style updates. I have not included them as it looks a bit overwhelming, let me know if you think we should include it somehow.
=> Update changelog for v0.21.0

bin/package.js, package-lock.json, package.json
Attempting to get the repo in shape to do a release!
=> electron-packager@^14.0.4

package-lock.json, package.json, src/main/windows/about.js, src/main/windows/main.js, src/main/windows/webtorrent.js
I tested basic functionality and all looks good so far :)
=> Update to Electron 5

src/renderer/webtorrent.js
sets the version the same way webtorrent dose it
https://github.com/webtorrent/webtorrent/blob/f8923a66a8b1178a412b067bc913e267025b3d57/index.js#L27-L29
=> Removed zero-fill

package-lock.json, package.json, src/renderer/pages/player-page.js
removes zero-fill as requested by @feross 
supersede #1583
btw, if it would be possible i would like to have a private chat with you @feross if that's okey with you.
=> remove zero fill at the final place

bin/package.js
For: https://github.com/webtorrent/webtorrent-desktop/issues/1637
=> Stop shipping 32-bit binaries

bin/open-config.js, package-lock.json, package.json
Address issue #1667, update opn dependency to [open](https://www.npmjs.com/package/open)
=> #1667 rename dependency opn to open

src/renderer/components/open-torrent-address-modal.js, src/renderer/lib/torrent-player.js
See: #1495 for more information.
=> Auto populate 'Magnet Link' field with the address from clipboard

src/config.js, src/main/menu.js
[ ] Bug fix
[X] New feature
Added new options in help menu: 'Release Notes' and 'Follow us on Twitter'.
See Issues #1670 and #1671 for more information
This is just a minor addition so there isn't anything to really focus on
=> Added 'Release notes' and 'follow on twitter' options in help

src/renderer/controllers/torrent-controller.js, src/renderer/main.js, src/renderer/webtorrent.js
=> Store magnet URI once torrent has been parsed

bin/package.js
[ ] Bug fix
Ensure that .deb and .zip files are created (with architecture in filename)
=> Add linux arm64 build (Fixes for PR #1650)

src/renderer/controllers/torrent-list-controller.js
Making the save file dialog sync to ensure working properly on MacOS ……and others
[X ] Bug fix
Changed the used method in `torrent-list-controller.js`
#1741
Code quality (for improving)
=> Fix for issue #1741 (Save Torrent File As...)

static/about.html
[x] Bug fix
Show directly current architecture exposed by `process.arch` e.g: `arm64`, `x32`, `x64`
Removes architecture parsing that only takes account `x64` or others
=> Show all supported architectures

package-lock.json, package.json, src/crash-reporter.js, src/main/index.js, src/main/windows/about.js, src/main/windows/main.js, src/main/windows/webtorrent.js, src/renderer/main.js, src/renderer/webtorrent.js
[ ] Bug fix
Update to Electron 10
There's a security fix in Electron 10 that I want to get out to users ASAP. Electron 10 is a beta version, but in my testing it seems to work just fine. The stable version will be released on 2020-08-25 according to their [Release Schedule](https://www.electronjs.org/docs/tutorial/electron-timelines).
If WebTorrent maintainers can please focus on testing this for bugs. We can do another quick release or two if we need to update to future Electron 10 betas to …
=> Update to Electron 10 beta

src/renderer/lib/media-extensions.js
[ ] Bug fix
[X] New feature
Add m2ts video container extension support.
This PR allows to identify `.m2ts` extension as a valid video file and play it throw VLC.
=> Add m2ts video container support

src/renderer/main.js
[ ] Bug fix
[x] Other, please explain: Removing usage of deprecated API
Don't rely on deprecated return value from ReactDOM.render
None. This is going to be a rule in the next version of `standard`.
=> Don't rely on deprecated return value from ReactDOM.render

package-lock.json, package.json, src/renderer/pages/player-page.js
[ ] Bug fix
[x] Other, please explain: Update deps
bitfield@4
https://github.com/webtorrent/webtorrent/issues/1951
=> bitfield@4

bin/package.js
[x] Bug fix
Add lintian overrides so we don't show the warnings while installing the package. 
https://github.com/webtorrent/webtorrent-desktop/issues/1844
=> Fix lintian warnings

src/renderer/pages/player-page.js, src/renderer/pages/torrent-list-page.js
[X] Bug fix
There were some incorrectly formatted unit symbols and units names in
the app, so this commit fixes them per SI and ISO/IEC specifications.
N/A
Everything
=> Fix formatting of measurement units

src/renderer/controllers/torrent-list-controller.js, src/renderer/main.js, src/renderer/pages/torrent-list-page.js, static/main.css
[ ] Bug fix
[X] New feature
~Add a context menu to paste a torrent address~
Paste torrent address with right click
Closes #834
None
=> feat: paste torrent address with right click

src/renderer/lib/time.js, src/renderer/pages/player-page.js, src/renderer/pages/torrent-list-page.js
[ ] Bug fix
[x] Other, please explain:
ETA calculation refactoring
Refactored ETA calculation
[1902](https://github.com/webtorrent/webtorrent-desktop/issues/1902)
=> refactor: ETA calculation

src/renderer/components/header.js
This makes screen readers properly indicate the control name, type, and state for the Back, Forward, and Add buttons.
=> fix(accessibility): Fix roles and add correct label for navigation controls

src/renderer/pages/player-page.js
[ ] Bug fix
[X] Other, please explain:
Improved the accessibility of the player
=> A11y: Added roles and labels to the playback controls

src/renderer/pages/player-page.js
Added support for the chrome `mediaSession` API so that hardware play/pause/next/back buttons will work to control the player
N/A
=> feat(Player Page): Add support for mediaSession

README.md
Replace deprecated Travis shield with GitHub Action CI shield
None. minor change
N/A
=> Fix CI shield in README
